### ISSUE TITLE
bert合成速度突然变得非常慢

### ISSUE THREAD

**Issue by Cosplayeridol** [Artrajz/vits-simple-api#101]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：win11
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：整合包
* Python 版本 (如果是部署包可不填)：3.10
* 代码版本/部署包版本:alpha.11

## 问题描述
项目部署到本地，但是前几天合成速度突然变得非常慢，以为换到最新版本可以解决，但是并没有（之前用alpha7的版本），现在平均合成速度150-200s左右，甚至有500s的情况，实在慢的离谱，不知道什么原因，求解决方案
## 问题复现步骤
![image](https://github.com/Artrajz/vits-simple-api/assets/85826393/a72bbb41-bb69-4914-bbea-3dcd62990bad)
![image](https://github.com/Artrajz/vits-simple-api/assets/85826393/18f8e674-3c2f-4f25-a11f-6ec0e1d1eed5)

**Comment by Cosplayeridol** [comment]
另外这个api，通过url粘贴到浏览器访问是无效的
![image](https://github.com/Artrajz/vits-simple-api/assets/85826393/a29b396b-afac-400b-a563-a724d5c17d65)

**Comment by Artrajz** [comment]
可以看看显存使用了多少，如果使用到了共享显存，那推理可能是会变慢的。

**Comment by Cosplayeridol** [comment]
> 可以看看显存使用了多少，如果使用到了共享显存，那推理可能是会变慢的。

我之前后台开五六个程序，bert合成起来都一直很快，不知道为什么突然变成了这样，我没有动任何设置，我用的一直是gpu版本的整合包，如果用了共享显存，要怎么解决这个问题？

**Comment by Artrajz** [comment]
首先是在任务管理器确认是否用到了共享显存。如果用到了共享显存，就说明显存用满了，只能尝试少加载一点模型，或者少加载bert模型。

**Comment by Artrajz** [comment]
看样子确实是使用了共享显存，这种情况下是会合成得非常慢。显存不够大目前我也没什么办法，可以试下直接用cpu推理，或者部署到另一台服务器调用。

**Comment by Cosplayeridol** [comment]
看来还是设备的性能到了瓶颈....我推流时调用云端api会比本地合成快不少，CPU的我也试试，本子的性能还是够呛😅
