### ISSUE TITLE
【需求】vits-fast-f-t 的支持

### ISSUE THREAD

**Issue by Ikaros-521** [Artrajz/vits-simple-api#102]
如题

**Comment by Artrajz** [comment]
这个需求是指训练吗？这个api不考虑加入训练功能哦

**Comment by Ikaros-521** [comment]
> 这个需求是指训练吗？这个api不考虑加入训练功能哦

仅推理，训练就不用了hhh

**Comment by Artrajz** [comment]
推理的话其实都是一样的，训练和推理都是基于moegoe和该作者的其他项目改造而来，所以也可以说已经支持了😂

**Comment by Ikaros-521** [comment]
> 推理的话其实都是一样的，训练和推理都是基于moegoe和该作者的其他项目改造而来，所以也可以说已经支持了😂

啊 我看文档没写 还以为不支持 那没事了
