### ISSUE TITLE
找不到文件/Model/hubert-soft-0d54a1f4.pt

### ISSUE THREAD

**Issue by LiuHua20** [Artrajz/vits-simple-api#104]
## 运行环境
win11 python3.10
* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

## 问题描述
模型为vits4.1训练
config.py文件的74行中HUBERT_SOFT_MODEL提示找不到路径（/Model/hubert-soft-0d54a1f4.pt），看代码也没有生成文件，但是我演示视频（b站）是没有任何修改的，是模型问题吗，还是什么

**Comment by Artrajz** [comment]
你说的vits4.1应该是指sovits4.1吧，这个项目主要支持的是tts的vits，不支持sovits

**Comment by LiuHua20** [comment]
谢谢回复，了解
