### ISSUE TITLE
想问问生成的音频文件音量有点小，可以修改音量吗，还是说是根据模型数据集限定的

### ISSUE THREAD

**Issue by cat-undertale** [Artrajz/vits-simple-api#114]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：Linux
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：自己搭的环境
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

## 问题描述
音量过小

**Comment by Artrajz** [comment]
api内暂时无法调整音量，可以生成之后再用ffmpeg之类的工具调整音量。模型输出音量具体跟什么有关我也不懂 😢

**Comment by JhonSmith0x7b** [comment]
https://stackoverflow.com/a/14030941/5017689  生成的音频ndarray直接乘可以调整音量, 但是会有点失真.
