### ISSUE TITLE
maxContentLength size of -1 exceeded 关于 这个报错具体该怎么处理

### ISSUE THREAD

**Issue by OriX0** [Artrajz/vits-simple-api#116]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：windows
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：自己搭的环境
* Python 版本 (如果是部署包可不填)：3.10
* 代码版本/部署包版本:

## 问题描述
搭建的环境，本地持续调用生成，部分情况会返回该报错，config.py里面的contentLength是默认的，我的单句长度也是控制在30个字内的。
同样的句子内容不是百分百出现，且出现情况的句子长度是不一样的

**Comment by Artrajz** [comment]
我这里无法复现该错误，之前也没遇到过这个错误，所以也不知道怎么解决

**Comment by OriX0** [comment]
> 我这里无法复现该错误，之前也没遇到过这个错误，所以也不知道怎么解决

- 目前是使用场景：run server 然后本地映射，其他机子调用。是队列式的生成
- 错误出现概率:不是百分百，平均100次出现2-3次，内容也不是固定的
- 目前排查下来配和gpt猜测原因：服务返回的content_length与实际wav的size不一致，导致了这个问题

**Comment by Artrajz** [comment]
这里发送音频都是使用flask的send_file函数，返回的content_length也是由flask自动控制的，想不出会有什么原因会导致和实际size不一致 😢 
会不会是flask版本不同，安装的flask版本和requirements.txt中的版本一致吗？

**Comment by OriX0** [comment]
> 这里发送音频都是使用flask的send_file函数，返回的content_length也是由flask自动控制的，想不出会有什么原因会导致和实际size不一致 😢 会不会是flask版本不同，安装的flask版本和requirements.txt中的版本一致吗？

确认了一下是2.2.3

**Comment by OriX0** [comment]
改成直接调用本地后再无出现本错误 应该是映射服务的问题
