### ISSUE TITLE
中英推理时还是会停顿，bert vits2官方修复了多语切换停顿的这个问题，大佬能把这个问题修复下吗？

### ISSUE THREAD

**Issue by ty10235270** [Artrajz/vits-simple-api#123]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

**Comment by Artrajz** [comment]
已更新https://github.com/Artrajz/vits-simple-api/commit/5cb09be868bed83e69801d942804b7fd024dd20e
