### ISSUE TITLE
bert-vits2 config文件

### ISSUE THREAD

**Issue by xinhecuican** [Artrajz/vits-simple-api#125]
## 问题描述
下载了bert-vits2 2.3的底模，然后从bert-vits2的v2.3tag上下载config文件，然后运行时speakerid没一个对应上的，config文件要去哪里找啊

**Comment by Artrajz** [comment]
官方发布的底模裁减了说话人层，所以在推理时speakers完全是随机的，这个没办法，只能基于底模自己训练。
