### ISSUE TITLE
大佬，Bert vits2开发者那边优化了特化版推理的显存占用，能不能安排一下？

### ISSUE THREAD

**Issue by ty10235270** [Artrajz/vits-simple-api#128]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

**Comment by Artrajz** [comment]
已更新 https://github.com/Artrajz/vits-simple-api/releases/tag/v0.6.6
