### ISSUE TITLE
为啥我用bv2开发者启智上分享的特化版1.3B bert不能用，必须要这个4.7G的，这个比bv2开发者的那个大一倍

### ISSUE THREAD

**Issue by ty10235270** [Artrajz/vits-simple-api#132]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

**Comment by ty10235270** [comment]
用bv2开发者那个就胡言乱语的

**Comment by Artrajz** [comment]
测试了一下确实有这个问题，但是我还找不到是哪里改出了错误，v0.6.5还是正常的，已经汗流浃背了。。

**Comment by gushuaialan1** [comment]
我也发现这个问题了，0.65是正常的，新版本就出鸟语了

**Comment by Artrajz** [comment]
`style_text`输入空文本，比如`""`可以用。暂时先这样

**Comment by Artrajz** [comment]
v0.6.7已修复该问题
