### ISSUE TITLE
新版本加载模型能否智能一点

### ISSUE THREAD

**Issue by yknBugs** [Artrajz/vits-simple-api#133]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：Windows 11
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：git clone 自己部署
* Python 版本 (如果是部署包可不填)：3.10.8
* 代码版本/部署包版本: v0.6.6

## 问题描述

最新版本的自动加载模型，会自动把不用于推理的D模型也给加载了，然后控制台会有一堆 xxx is not in the checkpoint的报错，并且网页选择说话人的id也会多出许多干扰项。

## 问题复现步骤

把训练完成的那几个模型全部扔到data文件夹里面，G模型和D模型都会被加载。然后控制台一堆报错，选择说话人id也会多出一堆。必须把D模型给删了，保证data文件夹里面只有G模型和config文件才能正常使用。

此外，能否给说话人加个名称搜索功能，我这上千个说话人网页ui上找的有些痛苦（

**Comment by Artrajz** [comment]
可以，下个版本加
