### ISSUE TITLE
加载模型的时候会出现错误 Model loading failed!

### ISSUE THREAD

**Issue by huwopi** [Artrajz/vits-simple-api#135]
## 运行环境

* 操作系统  ubuntu
* 部署方式 Docker
* 代码版本/部署包版本:最新的

## 问题复现步骤
加载模型的时候会出现错误 Model loading failed! 

这个是日志
![2024-01-25_052938](https://github.com/Artrajz/vits-simple-api/assets/157674825/f0f17282-1791-4387-9788-e35703e895fe)

**Comment by Artrajz** [comment]
请问使用的是hubert-vits模型吗
