### ISSUE TITLE
特定词组单独推理无法返回音频

### ISSUE THREAD

**Issue by DengHao97** [Artrajz/vits-simple-api#141]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

## 问题描述

![1706683413414](https://github.com/Artrajz/vits-simple-api/assets/96048553/0edcdb18-9437-40c6-a42e-eecedc725a80)
一些字或者词单独出现的时候无法获取音频
比如“我喊道”，“发热”，“囊肿等”
## 问题复现步骤
单独输入
“我喊道”，“发热”，“囊肿等”
词组进行音频推理

**Comment by Artrajz** [comment]
这是由于语种识别库将其识别为了日文进行处理，自然就出错了。语种识别目前对于比较短的句子准确率不高，这种情况必须手动指定`lang=zh`，或者在config.json中排除日语`lang: ["zh", "en"]`
