### ISSUE TITLE
管理员后台已加载模型但是网页前端不显示

### ISSUE THREAD

**Issue by My-Noir** [Artrajz/vits-simple-api#145]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：win11
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：快速部署包
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:v0.6.7

## 问题描述
大佬您好，我想用您的项目加载另一个大佬训练的模型，是moetts的，但是管理员后台显示已经加载可网页前端还是没有加载模型，本来它还报错要一个hubert-soft模型但是我自己加了进去就不报错了。
加入hubert-soft模型前报错：
![屏幕截图 2024-02-08 154127](https://github.com/Artrajz/vits-simple-api/assets/78475068/3ef0b588-f81a-4be0-86fe-74939179ffc3)
加入后情况：

![屏幕截图 2024-02-08 154337](https://github.com/Artrajz/vits-simple-api/assets/78475068/a789a3ec-694c-4db9-9acb-1c1532d17dc6)

![屏幕截图 2024-02-08 154345](https://github.com/Artrajz/vits-simple-api/assets/78475068/a2776175-4422-469b-9873-f0526669d7fc)

运行截图：

![屏幕截图 2024-02-08 155216](https://github.com/Artrajz/vits-simple-api/assets/78475068/4447e8ba-876c-4073-888b-132361870206)

没报错但是还是没加载模型

## 问题复现步骤
就是正常加载模型

希望大佬抽空解答我的疑惑，万分感谢

**Comment by Artrajz** [comment]
由于hubert-vits太少人用了，并且它不是tts，而是变声模型，所以没有写对应的网页（懒癌）。

如果要用的话，之后可以加上hubert-vits的页面。

**Comment by Artrajz** [comment]
tts是文字转语音，而变声模型是输入音频->输出音频。hubert-vits他们都有vits的结构，但功能和目的上来说是不一样的

**Comment by My-Noir** [comment]
好的，明白了，谢谢您
