### ISSUE TITLE
希望大佬支持日语特化版

### ISSUE THREAD

**Issue by gushuaialan1** [Artrajz/vits-simple-api#147]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:0.69
## 问题描述
日文特化版模型推理异常，不能正常推理。看了下代码版本2.4里面并没有载入日语推理模型。希望大佬支持日语特化版

**Comment by gushuaialan1** [comment]
版本号改成2.3能推理

**Comment by gushuaialan1** [comment]
> 版本号改成2.3能推理

但是推理之后的语气完全不正确

**Comment by Artrajz** [comment]
久等了，已更新 https://github.com/Artrajz/vits-simple-api/commit/6c619cc806cea6a63dc310e52e0c16da2b025d66
