### ISSUE TITLE
请问怎样可以与SillyTavern连接？

### ISSUE THREAD

**Issue by barbasting** [Artrajz/vits-simple-api#153]
大佬好，vits-simple-api可以和SillyTavern连接吗？有什么方式方法请指教多谢。

**Comment by Artrajz** [comment]
我还不熟悉SillyTavern，有大佬写了脚本 https://github.com/yujianke100/vits-simple-api-for-SillyTavern ，不过你应该已经找到了(

**Comment by barbasting** [comment]
是呀，自己过于小白，有想法只好找各位大佬求助了，感谢回复
