### ISSUE TITLE
gpt sovits，你好，生成语音重复

### ISSUE THREAD

**Issue by kingslyChen** [Artrajz/vits-simple-api#155]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：linux
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：linux
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:v0.6.11

## 问题描述
目前使用同样的模型文件，引导音频和文本在推理界面生成的语音我测试了20次是没有重复问题的，但是在该项目上生成的是大概率会重复，例如：八八八   ，请问是哪个配置差异导致的还是？

**Comment by Artrajz** [comment]
应该是上个版本中把给“八八八”这样的短文本前面加标点的代码误删了，现在加回去并重新发了一次版本

**Comment by kingslyChen** [comment]
> 另外更新了官方选择seed的功能，同样的seed推理出来的音频有点差别，我对比过核心的代码是与官方保持一致的，文本切分的代码不同但结果应该也是一致的（短文本），尚不清楚是什么导致的差异 😭

现在中文的没重复了。中英的还有问题是不是中英处理的部分没改回去？😭

**Comment by Artrajz** [comment]
中英有问题吗？能给一些有问题的推理例句吗？

**Comment by kingslyChen** [comment]
> 中英有问题吗？代码应该没有少的了，能给一些有问题的推理例句吗？

例如：我最爱这个大V DD-i 这个是有问题的 很容易出现重复，我最爱这个大V滴滴挨 用这中文的同音的就没有重复

**Comment by Artrajz** [comment]
这个不是中英的问题，是GPT-SoVITS还不难很准确地读字母，用官方代码也是如此
