### ISSUE TITLE
在docker上部署时出错

### ISSUE THREAD

**Issue by ken0414** [Artrajz/vits-simple-api#16]
在docker上部署时出现以下错误：

INFO:moegoe-simple-api:角色id：0
INFO:moegoe-simple-api:合成文本：[ZH]您好！有什么我可以帮助您的吗？[ZH]
ERROR:app:Exception on /voice [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app.py", line 80, in voice_api
    output, file_type, fname = real_obj.generate(text=text,
  File "/app/voice.py", line 100, in generate
    stn_tst = self.get_text(text, self.hps_ms, cleaned=cleaned)
  File "/app/voice.py", line 56, in get_text
    text_norm = text_to_sequence(text, hps.symbols, hps.data.text_cleaners)
  File "/app/text/__init__.py", line 17, in text_to_sequence
    clean_text = _clean_text(text, cleaner_names)
  File "/app/text/__init__.py", line 31, in _clean_text
    text = cleaner(text)
  File "/app/text/cleaners.py", line 118, in shanghainese_cleaners
    from text.shanghainese import shanghainese_to_ipa
  File "/app/text/shanghainese.py", line 6, in <module>
    converter = opencc.OpenCC('zaonhe')
  File "/usr/local/lib/python3.9/site-packages/opencc/__init__.py", line 43, in __init__
    super(OpenCC, self).__init__(config)
RuntimeError: /usr/local/lib/python3.9/site-packages/opencc/clib/share/opencc/zaonhe.json not found or not accessible.
INFO:werkzeug:172.30.0.1 - - [10/Apr/2023 13:28:30] "GET /voice?text=您好！有什么我可以帮助您的吗？&lang=zh&id=0&format=silk&length=1.4 HTTP/1.1" 500 -

请问是什么原因

**Comment by Artrajz** [comment]
请问您是否使用了上海方言的模型？这个问题我也是第一次遇见，貌似是opencc缺少zaonhe.json，目前我还未找到解决方法，抱歉！

**Comment by Artrajz** [comment]
> 请问您是否使用了上海方言的模型？这个问题我也是第一次遇见，貌似是opencc缺少zaonhe.json，目前我还未找到解决方法，抱歉！

已添加zaonhe.json，您可以等待最新的docker构建完成后（显示绿色的勾），拉取最新镜像并使用

**Comment by ken0414** [comment]
> > 请问您是否使用了上海方言的模型？这个问题我也是第一次遇见，貌似是opencc缺少zaonhe.json，目前我还未找到解决方法，抱歉！
> 
> 已添加zaonhe.json，您可以等待最新的docker构建完成后，拉取最新镜像并测试一下

非常感谢，我会在之后测试的！

**Comment by lao-zei** [comment]
![Screenshot_2023-04-19-13-14-05-243-edit_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/232973165-38bab3af-8996-4a73-a4f4-cbafb9a9fdc8.jpg)

![Screenshot_2023-04-19-13-13-07-815-edit_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/232973177-5409926c-d363-4087-9710-857618fbb580.jpg)

> 我好像遇到了相同的问题是刚部署的用的好像也是最新的镜像请问这个怎么处理

**Comment by Artrajz** [comment]
> ![Screenshot_2023-04-19-13-14-05-243-edit_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/232973165-38bab3af-8996-4a73-a4f4-cbafb9a9fdc8.jpg)
> 
> ![Screenshot_2023-04-19-13-13-07-815-edit_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/232973177-5409926c-d363-4087-9710-857618fbb580.jpg)
> 
> > 我好像遇到了相同的问题是刚部署的用的好像也是最新的镜像请问这个怎么处理

你的问题和上面的不一样，报错的是id超出范围，检查下导入的模型，贴一下你的配置文件

**Comment by lao-zei** [comment]
> > ![Screenshot_2023-04-19-13-14-05-243-edit_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/232973165-38bab3af-8996-4a73-a4f4-cbafb9a9fdc8.jpg)
> > 
> > ![Screenshot_2023-04-19-13-13-07-815-edit_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/232973177-5409926c-d363-4087-9710-857618fbb580.jpg)
> > 
> > > 我好像遇到了相同的问题是刚部署的用的好像也是最新的镜像请问这个怎么处理
> 
> 你的问题和上面的不一样，报错的是id超出范围，检查下导入的模型，贴一下你的配置文件

![Screenshot_2023-04-19-16-38-27-027_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/233018823-55f19ec2-8b5f-45e2-8d47-051f83171dcc.jpg)

![Screenshot_2023-04-19-16-45-12-293-edit_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/233020512-304153a8-fcf9-4235-a997-cb8cd10a8c8a.jpg)

模型我直接放到Model了

![Screenshot_2023-04-19-16-43-04-598-edit_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/101307321/233020674-e469bdbd-265d-4549-a041-1ee8ba2fd6b2.jpg)

这是我用的模型在https://github.com/CjangCjengh/TTSModels#chinese--japanese下载的
