### ISSUE TITLE
GPT的GPT_SoVITS/text/engdict-hot.rep 配置文件怎么配置？

### ISSUE THREAD

**Issue by kingslyChen** [Artrajz/vits-simple-api#161]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

## 问题描述
GPT的GPT_SoVITS/text/engdict-hot.rep文件怎么配置？

**Comment by Artrajz** [comment]
不太了解这个，看起来是指定一个单词的读音，具体可以去GPT-SoVITS官方项目下面问问
