### ISSUE TITLE
关于动态加载 gpt_sovits 的指定模型，我克隆生成的模型能否有api可以直接设置，而不需要在配置文件中配置 然后重启服务器才能用

### ISSUE THREAD

**Issue by anstonjie** [Artrajz/vits-simple-api#165]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：Windows11
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：自己搭的环境
* Python 版本 (如果是部署包可不填)：Python 10
* 代码版本/部署包版本:  最新版本

## 问题描述
关于动态加载 gpt_sovits 的指定模型，我克隆生成的模型能否有api可以直接设置，而不需要在配置文件中配置 然后重启服务器才能用

**Comment by Artrajz** [comment]
先将模型放到和之前的模型一样放到data/models下，然后浏览器访问/admin管理界面，可以找到刚刚放进去的模型，点击它等待一会就可以加载了，不需要重启服务器

**Comment by anstonjie** [comment]
那他在api里面不用配置可以直接调用吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月19日 15:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Artrajz/vits-simple-api] 关于动态加载 gpt_sovits 的指定模型，我克隆生成的模型能否有api可以直接设置，而不需要在配置文件中配置 然后重启服务器才能用 (Issue #165) |

先将模型放到和之前的模型一样放到data/models下，然后浏览器访问/admin管理界面，可以找到刚刚放进去的模型，点击它等待一会就可以加载了，不需要重启服务器

**Comment by Artrajz** [comment]
加载成功后和服务器启动时加载的模型一样使用，不需要额外配置
