### ISSUE TITLE
分词语言检测问题

### ISSUE THREAD

**Issue by grider-withourai** [Artrajz/vits-simple-api#173]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：Linux
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：Docker
* 代码版本/部署包版本: v0.6.12

## 问题描述
bert-vits2语言设置为audo，当遇到`ご主人様`时会读成中文的主人样而不是日文，如在`それは残念だったわね、ご主人様。`内。

**Comment by Artrajz** [comment]
建议语言直接写ja。目前的auto是先按标点符号切分再进行识别的，而语种识别库对中日文的短文本识别不佳，从而导致了有时中文识别为日文、日文识别为中文的情况。

**Comment by grider-withourai** [comment]
可以选择分割的符号吗，我觉得顿号，逗号这些可以不用分割的，如果不用这些分割我觉得正确识别的概率会比较大。

**Comment by Artrajz** [comment]
做了一次更新 https://github.com/Artrajz/vits-simple-api/commit/68cdddae905b5ce19b07ee7c556e150828a449d0 可以在config.yaml中修改split_pattern的正则表达式，在这里去掉顿号，逗号。

**Comment by grider-withourai** [comment]
好像可以了，谢谢。
