### ISSUE TITLE
我训练了so-vits模型放入了model，但显示没有加载任何模型

### ISSUE THREAD

**Issue by HMSXEF** [Artrajz/vits-simple-api#175]
![IMG_20240809_110945.jpg](https://github.com/user-attachments/assets/07400fcb-7cd4-4f21-a7d4-2b77e2c11347)

**Comment by CPF471112809** [comment]
同问

**Comment by HongXingDeveloper** [comment]
> 同问
> 

模型练炸了）虽然不知道什情况，提完问题自己好了）
