### ISSUE TITLE
这个项目的底膜发个链接，我各种底膜用了版本都不对

### ISSUE THREAD

**Issue by li771667481** [Artrajz/vits-simple-api#182]
## 运行环境

* 操作系统 (Linux/macOS/Windows)：
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本:

**Comment by gushuaialan1** [comment]
> ## 运行环境
> * 操作系统 (Linux/macOS/Windows)：
> * 部署方式 (Docker/windows快速部署包/自己搭的环境)：
> * Python 版本 (如果是部署包可不填)：
> * 代码版本/部署包版本:
> 
> ## 问题描述
> ## 问题复现步骤

……

**Comment by Artrajz** [comment]
这个是推理项目，没有训练功能也没有底模。至于版本不对请查看日志报错问题
