### ISSUE TITLE
加载模型失败

### ISSUE THREAD

**Issue by ORO44** [Artrajz/vits-simple-api#183]
## 运行环境

* 操作系统 (Linux/macOS/Windows)： linux
* 部署方式 (Docker/windows快速部署包/自己搭的环境)：docker
* Python 版本 (如果是部署包可不填)：
* 代码版本/部署包版本: 最新
## 问题描述

加载模型失败emmm..

加载模型识别
![image](https://github.com/user-attachments/assets/36551ca7-c59e-401d-83a4-a1c7a1c7185d)

**Comment by Artrajz** [comment]
缺少chinese_hubert_base导致加载失败，可以自行下载[chinese-hubert-base/pytorch_model.bin](https://hf-mirror.com/TencentGameMate/chinese-hubert-base/resolve/main/pytorch_model.bin)或从官方整合包复制，放到`data\hubert\chinese_hubert_base`

和下载[chinese-roberta-wwm-ext-large/pytorch_model.bin](https://hf-mirror.com/hfl/chinese-roberta-wwm-ext-large/resolve/main/pytorch_model.bin)或从官方整合包复制，放到`data\bert\chinese-roberta-wwm-ext-large`

正常情况缺少这些模型会自动下载，应该是网络问题下载失败

**Comment by ORO44** [comment]
> 缺少chinese_hubert_base导致加载失败，可以自行下载[chinese-hubert-base/pytorch_model.bin](https://hf-mirror.com/TencentGameMate/chinese-hubert-base/resolve/main/pytorch_model.bin)或从官方整合包复制，放到`data\hubert\chinese_hubert_base`
> 
> 检查`data\bert\chinese-roberta-wwm-ext-large`有没有pytorch_model.bin，如果没有就下载[chinese-roberta-wwm-ext-large/pytorch_model.bin](https://hf-mirror.com/hfl/chinese-roberta-wwm-ext-large/resolve/main/pytorch_model.bin)或从官方整合包复制
> 
> 正常情况缺少这些模型会自动下载，应该是网络问题下载失败

十分感谢, 可以加载了
