### ISSUE TITLE
VITS without [JA]

### ISSUE THREAD

**Issue by himekifee** [Artrajz/vits-simple-api#21]
Hi. Thanks for your contribution to the project. I had an issue using your project with a trained model from [vits-finetuning](https://github.com/SayaSS/vits-finetuning). It speaks that [JA] in the generated audio file. Is there a way to prevent that? Thanks.

**Comment by Artrajz** [comment]
I would like to know what lang you pass in when calling the api, generally [JA] will not be added to the speech, unless inferred with redundant [JA].For example, [JA] is automatically added when lang=ja, in this case, the text does not need to add [JA].

**Comment by himekifee** [comment]
Running the latest docker, the language is Japanese, and in `config.py`, it is `LANG = "AUTO"`. Though passing a simple Japanese greeting will speak with that `JA こんにちは JA`.

**Comment by Artrajz** [comment]
`JA こんにちは JA` the usage is wrong, "auto" will automatically mark language, it just need to use `こんにちは`

**Comment by himekifee** [comment]
I mean, I input `curl "127.0.0.1:23456/voice?text=%E3%81%93%E3%82%93%E3%81%AB%E3%81%A1%E3%81%AF"` which is only `こんにちは`, but the output wave speaks `JA こんにちは JA`.

**Comment by Artrajz** [comment]
It is a strange problem,it didn't speak `JA こんにちは JA` in my demo`https://api.artrajz.cn/py/voice?text=こんにちは`

**Comment by himekifee** [comment]
I thought it was a training issue that the training dataset contained [JA], but the audio file does not have it, so the network learnt that. Though it does not seem to be the case. Might be an issue with the VITS config file. Would you like a copy of the model and config file?

**Comment by Artrajz** [comment]
yes,please.

**Comment by himekifee** [comment]
Sent to your qq mail

**Comment by Artrajz** [comment]
I will check it tomorrow because it is too late now. Sorry for the inconvenience.

**Comment by himekifee** [comment]
Take your time. Do it when you have extra free time. Thanks a lot for your help.

**Comment by Artrajz** [comment]
I downloaded the pre-trained model and I think I found the reason. For a single language cleaner like japanese_cleaners, there is no need for [JA] annotation in inference. However, the program automatically adds [JA] when lang=auto or lang=ja. Now I have changed all the cleaners to require language annotation to clean. 07021e4

**Comment by himekifee** [comment]
Brilliant. It indeed works now. Thanks a lot.
