### ISSUE TITLE
如何实现gpu推理

### ISSUE THREAD

**Issue by t4wefan** [Artrajz/vits-simple-api#22]
我发现这个默认只能cpu推理，即便我有48核但是还是慢而且吃不满，但是我这还有3090，我想用gpu可以大幅度加速推理

**Comment by Artrajz** [comment]
我会在后续加入可选GPU推理的

**Comment by Artrajz** [comment]
> 我会在后续加入可选GPU推理的

已加入GPU推理 0a4e02f，需要手动安装cuda和gpu版的pytorch，步骤可以参考文档
