### ISSUE TITLE
不是很懂python求助路径问题

### ISSUE THREAD

**Issue by hisou** [Artrajz/vits-simple-api#24]
clone项目到服务器上后，下一步，模型库以及`config.py`都要放到服务器根路径的`/path/to/....`？ 但是在`app.py`里读取`config.py`的时候却没有指定`ABS_PATH`，应该是直接在同级目录下加载，这样能找到吗？感觉有一点反直觉，想确认一下

**Comment by Artrajz** [comment]
`/path/to/`目录是指到项目根目录的路径，因为每个人clone的位置是不同的，所以用`/path/to/`指代。clone项目之后你只需要按照示例，把模型放到项目根目录的Model文件夹下，然后修改config.py中的模型路径即可。

**Comment by hisou** [comment]
> `/path/to/`目录是指到项目根目录的路径，因为每个人clone的位置是不同的，所以用`/path/to/`指代。clone项目之后你只需要按照示例，把模型放到项目根目录的Model文件夹下，然后修改config.py中的模型路径即可。`app.py`中确实是在同级目录下读取config.py，所以不需要移动config.py。 `ABS_PATH`是在config.py定义了`ABS_PATH = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])))`，这句话可以获取项目根目录的路径，`ABS_PATH+"/Model/..."`组合就是模型的绝对路径，当然你也可以直接写模型的绝对路径，从而读取任何其他不在`Model`文件夹下的模型。

好吧谢谢，因为习惯默认`/`开头的就是系统根目录，所以特意确认一下
