### ISSUE TITLE
【功能请求】希望能添加防止公网服务器被滥用的鉴权功能

### ISSUE THREAD

**Issue by 2DIPW** [Artrajz/vits-simple-api#25]
作者您好：
目前vits-simple-api没有鉴权功能，这意味着部署在公网的vits-simple-api会响应所有请求，一旦服务器URL暴露，可能有被滥用的风险，建议考虑加入类似于api key的鉴权功能，谢谢！

**Comment by Artrajz** [comment]
这个提议不错，会在近期更新鉴权功能的。

**Comment by Artrajz** [comment]
> 这个提议不错，会在近期更新鉴权功能的。

已更新，目前的鉴权比较简单，只能设置单一api key。默认关闭，需要在config.py中启用，启用后在GET请求中使用需要增加参数api_key。

**Comment by 2DIPW** [comment]
感谢
