### ISSUE TITLE
ubanru22.04 docker环境下报错

### ISSUE THREAD

**Issue by lao-zei** [Artrajz/vits-simple-api#26]
![Screenshot_2023-04-23-12-22-01-969-edit_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/233819755-8eb790b9-d133-456d-b817-63a2fdb31160.jpg)

![Screenshot_2023-04-23-12-22-17-839_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/101307321/233819756-3ab14864-ca81-469c-be73-5e914c7e39f7.jpg)

作者又要麻烦你了
请问这是什么情况啊

**Comment by Artrajz** [comment]
方便发一下你的config.json吗，看样子是config.json格式出了问题

**Comment by lao-zei** [comment]
抱歉刚发现复制过去的是空白了 可能弄混了我再更新一下试试

**Comment by lao-zei** [comment]
你好作者重新上传后又出现这个错误

[E 230423 12:41:46 fastlid:41] <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>
ERROR: 1

**Comment by Artrajz** [comment]
这个是网络问题，fastlid初次运行需要下载一个700k的模型

**Comment by lao-zei** [comment]
要代理？

**Comment by lao-zei** [comment]
好了谢谢作者

**Comment by Artrajz** [comment]
我刚刚从[官网](https://fasttext.cc/docs/en/language-identification.html)试了下，下载模型不需要代理

**Comment by lao-zei** [comment]
我开了代理后下载下来了
可能是网络波动吧
