### ISSUE TITLE
大佬，可以吧你的模型共享出来吗？

### ISSUE THREAD

**Issue by jwister** [Artrajz/vits-simple-api#28]
如题

**Comment by Artrajz** [comment]
模型是其他大佬做的，你可以在这里找到我所使用的模型
https://github.com/CjangCjengh/TTSModels
https://huggingface.co/spaces/zomehwh/vits-uma-genshin-honkai/tree/main/model

**Comment by jwister** [comment]
您的邮件已收到，谢谢。

**Comment by jwister** [comment]
感谢，已经用起来了，现在的问题是在哪里开启gpu加速啊？有配置项吗？

**Comment by Artrajz** [comment]
> 感谢，已经用起来了，现在的问题是在哪里开启gpu加速啊？有配置项吗？

需要安装cuda和gpu版pytorch，安装好后会自动调用gpu。

**Comment by jwister** [comment]
安装好了，电脑也重启了，重新跑的时候还是没显示启用gpu加速。后面吧集成显卡禁用了，也没用，是我的显卡是mx250    是需要设置哪里吗？

**Comment by Artrajz** [comment]
> 安装好了，电脑也重启了，重新跑的时候还是没显示启用gpu加速。后面吧集成显卡禁用了，也没用，是我的显卡是mx250    是需要设置哪里吗？

你验证下cuda是否安装成功，mx250应该要找对应的版本安装。然后是pytorch，在vits启动时会打印pytorch版本信息，版本是x.x.x+cu11x（x是数字）的才是可以使用cuda的。

**Comment by cgnannan** [comment]
> 模型是其他大佬做的，你可以在这里找到我所使用的模型 https://github.com/CjangCjengh/TTSModels https://huggingface.co/spaces/zomehwh/vits-uma-genshin-honkai/tree/main/model

大佬，目前vits有英语模型么？今天在网上搜了半天，也没找到英语Model。

**Comment by Artrajz** [comment]
305cae870afcaf53d75b8edae5f10e1d8b3d87e9
在对应的json文件中添加以下两行才能使用
```
"speakers": ["vctk"],
"symbols":  ["_", ";", ":", ",", ".", "!", "?", "¡", "¿", "—", "…", "\"", "«", "»", "“", "”", " ", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "ɑ", "ɐ", "ɒ", "æ", "ɓ", "ʙ", "β", "ɔ", "ɕ", "ç", "ɗ", "ɖ", "ð", "ʤ", "ə", "ɘ", "ɚ", "ɛ", "ɜ", "ɝ", "ɞ", "ɟ", "ʄ", "ɡ", "ɠ", "ɢ", "ʛ", "ɦ", "ɧ", "ħ", "ɥ", "ʜ", "ɨ", "ɪ", "ʝ", "ɭ", "ɬ", "ɫ", "ɮ", "ʟ", "ɱ", "ɯ", "ɰ", "ŋ", "ɳ", "ɲ", "ɴ", "ø", "ɵ", "ɸ", "θ", "œ", "ɶ", "ʘ", "ɹ", "ɺ", "ɾ", "ɻ", "ʀ", "ʁ", "ɽ", "ʂ", "ʃ", "ʈ", "ʧ", "ʉ", "ʊ", "ʋ", "ⱱ", "ʌ", "ɣ", "ɤ", "ʍ", "χ", "ʎ", "ʏ", "ʑ", "ʐ", "ʒ", "ʔ", "ʡ", "ʕ", "ʢ", "ǀ", "ǁ", "ǂ", "ǃ", "ˈ", "ˌ", "ː", "ˑ", "ʼ", "ʴ", "ʰ", "ʱ", "ʲ", "ʷ", "ˠ", "ˤ", "˞", "↓", "↑", "→", "↗", "↘", "'", "̩", "'", "ᵻ"]
```

**Comment by cgnannan** [comment]
> [305cae8](https://github.com/Artrajz/vits-simple-api/commit/305cae870afcaf53d75b8edae5f10e1d8b3d87e9) 在对应的json文件中添加以下两行才能使用
> 
> ```
> "speakers": ["vctk"],
> "symbols":  ["_", ";", ":", ",", ".", "!", "?", "¡", "¿", "—", "…", "\"", "«", "»", "“", "”", " ", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "ɑ", "ɐ", "ɒ", "æ", "ɓ", "ʙ", "β", "ɔ", "ɕ", "ç", "ɗ", "ɖ", "ð", "ʤ", "ə", "ɘ", "ɚ", "ɛ", "ɜ", "ɝ", "ɞ", "ɟ", "ʄ", "ɡ", "ɠ", "ɢ", "ʛ", "ɦ", "ɧ", "ħ", "ɥ", "ʜ", "ɨ", "ɪ", "ʝ", "ɭ", "ɬ", "ɫ", "ɮ", "ʟ", "ɱ", "ɯ", "ɰ", "ŋ", "ɳ", "ɲ", "ɴ", "ø", "ɵ", "ɸ", "θ", "œ", "ɶ", "ʘ", "ɹ", "ɺ", "ɾ", "ɻ", "ʀ", "ʁ", "ɽ", "ʂ", "ʃ", "ʈ", "ʧ", "ʉ", "ʊ", "ʋ", "ⱱ", "ʌ", "ɣ", "ɤ", "ʍ", "χ", "ʎ", "ʏ", "ʑ", "ʐ", "ʒ", "ʔ", "ʡ", "ʕ", "ʢ", "ǀ", "ǁ", "ǂ", "ǃ", "ˈ", "ˌ", "ː", "ˑ", "ʼ", "ʴ", "ʰ", "ʱ", "ʲ", "ʷ", "ˠ", "ˤ", "˞", "↓", "↑", "→", "↗", "↘", "'", "̩", "'", "ᵻ"]
> ```

谢谢大佬，我试试去

**Comment by Artrajz** [comment]
不用，他在README里提供了预训练模型的下载链接，你可以直接使用预训练模型，或者在这个模型上继续训练。而json文件可以在仓库的[configs](https://github.com/jaywalnut310/vits/tree/main/configs)里找到

**Comment by cgnannan** [comment]
> > [305cae8](https://github.com/Artrajz/vits-simple-api/commit/305cae870afcaf53d75b8edae5f10e1d8b3d87e9) 在对应的json文件中添加以下两行才能使用
> > ```
> > "speakers": ["vctk"],
> > "symbols":  ["_", ";", ":", ",", ".", "!", "?", "¡", "¿", "—", "…", "\"", "«", "»", "“", "”", " ", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "ɑ", "ɐ", "ɒ", "æ", "ɓ", "ʙ", "β", "ɔ", "ɕ", "ç", "ɗ", "ɖ", "ð", "ʤ", "ə", "ɘ", "ɚ", "ɛ", "ɜ", "ɝ", "ɞ", "ɟ", "ʄ", "ɡ", "ɠ", "ɢ", "ʛ", "ɦ", "ɧ", "ħ", "ɥ", "ʜ", "ɨ", "ɪ", "ʝ", "ɭ", "ɬ", "ɫ", "ɮ", "ʟ", "ɱ", "ɯ", "ɰ", "ŋ", "ɳ", "ɲ", "ɴ", "ø", "ɵ", "ɸ", "θ", "œ", "ɶ", "ʘ", "ɹ", "ɺ", "ɾ", "ɻ", "ʀ", "ʁ", "ɽ", "ʂ", "ʃ", "ʈ", "ʧ", "ʉ", "ʊ", "ʋ", "ⱱ", "ʌ", "ɣ", "ɤ", "ʍ", "χ", "ʎ", "ʏ", "ʑ", "ʐ", "ʒ", "ʔ", "ʡ", "ʕ", "ʢ", "ǀ", "ǁ", "ǂ", "ǃ", "ˈ", "ˌ", "ː", "ˑ", "ʼ", "ʴ", "ʰ", "ʱ", "ʲ", "ʷ", "ˠ", "ˤ", "˞", "↓", "↑", "→", "↗", "↘", "'", "̩", "'", "ᵻ"]
> > ```
> 
> 谢谢大佬，我试试去

大佬，我先git pull了您最新的代码。然后加载了预训练模型，也将您这两行代码更新到模型对应的json文件，python.app后报出以下错误

(fort) E:\Fort\WechatBot\vits-simple-api>python app.py
INFO:root:Loaded checkpoint 'E:\Fort\WechatBot\vits-simple-api/Model/Nene_Nanami_Rong_Tang/1374_epochs.pth' (iteration None)
INFO:root:Loaded checkpoint 'E:\Fort\WechatBot\vits-simple-api/Model/Zero_no_tsukaima/1158_epochs.pth' (iteration None)
INFO:root:Loaded checkpoint 'E:\Fort\WechatBot\vits-simple-api/Model/g/G_953000.pth' (iteration 630)
INFO:root:Loaded checkpoint 'E:\Fort\WechatBot\vits-simple-api/Model/Voistock/547_epochs.pth' (iteration None)
INFO:root:Loaded checkpoint 'E:\Fort\WechatBot\vits-simple-api/Model/ljs/ljs.pth' (iteration 0)
Traceback (most recent call last):
  File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\torch\serialization.py", line 354, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Fort\WechatBot\vits-simple-api\app.py", line 28, in <module>
    tts = merge_model(app.config["MODEL_LIST"])
  File "E:\Fort\WechatBot\vits-simple-api\utils\merge.py", line 55, in merge_model
    obj = vits(model=i[0], config=i[1])
  File "E:\Fort\WechatBot\vits-simple-api\voice.py", line 54, in __init__
    self.load_model(model, model_)
  File "E:\Fort\WechatBot\vits-simple-api\voice.py", line 61, in load_model
    self.hubert = hubert_soft(model_)
  File "E:\Fort\WechatBot\vits-simple-api\hubert_model.py", line 217, in hubert_soft
    checkpoint = torch.load(path)
  File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\torch\serialization.py", line 276, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\torch\serialization.py", line 261, in __init__
    _check_seekable(buffer)
  File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\torch\serialization.py", line 357, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\torch\serialization.py", line 350, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

我将这两行代码放到了"train"下，是不是我放的位置不对
<img width="1665" alt="Screen Shot 2023-05-15 at 11 41 11 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/9be6d5f3-a112-4b7d-a140-fbd60ff77daf">

另外，他的configs中，ljs模型有两个json文件，我用的ljs_base.json
<img width="309" alt="Screen Shot 2023-05-15 at 11 44 10 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/6ed1a26a-7e32-43eb-83c8-65472d16d11a">

MODEL_LIST也同步更新了
<img width="1660" alt="Screen Shot 2023-05-15 at 11 45 53 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/85e8af83-aac8-423f-b93f-457ecd48677f">

**Comment by Artrajz** [comment]
在config.py中填写espeak的dll路径即可解决

**Comment by cgnannan** [comment]
> espeak

大佬，好像我下载的espeak版本不对，在对应目录下没有找到libespeak-ng.dll文件
在网上搜了一下，没找到Win10系统的eSpeak NG的exe安装文件，

找到了python[依赖库](https://pypi.org/project/espeakng/)和[github仓库](https://github.com/espeak-ng/espeak-ng/)

**Comment by Artrajz** [comment]
这个是win10可用的安装文件
https://github.com/espeak-ng/espeak-ng/releases/download/1.51/espeak-ng-X64.msi

**Comment by cgnannan** [comment]
> 这个是win10可用的安装文件 https://github.com/espeak-ng/espeak-ng/releases/download/1.51/espeak-ng-X64.msi

大佬，成功啦，可以接到请求并返回语音啦。试了id0和id1都是女声，是不是ljs和vctk这两个模型都是女声？想要英文男声，应该去哪里找啊？

**Comment by Artrajz** [comment]
看了下vctk的json中有109个speaker，你可以将json里的speaker名称任意补全，例如`"speakers": ["vctk1","vctk2","vctk3"],`然后再进行挑选。我试了下这个模型中id1就是男声。

**Comment by cgnannan** [comment]
> 看了下vctk的json中有109个speaker，你可以将json里的speaker名称任意补全，例如`"speakers": ["vctk1","vctk2","vctk3"],`然后再进行挑选。我试了下这个模型中id1就是男声。

大佬，我按照您的方案，已经将vctk1,vctk2，vctk3加载到config.json里了，运行服务后，在页面端(http://127.0.0.1:23456/voice/speakers)可以看到不同id号了

![无标题](https://github.com/Artrajz/vits-simple-api/assets/54965656/06f182f4-5006-49d1-b5cd-c4502d68cfe7)

是否意味着已经成功加载vctk的3个音库了，我只要在咱们仓库的config.py里改id选出来男声就可以了。


![无标题](https://github.com/Artrajz/vits-simple-api/assets/54965656/9a977abe-b524-4de7-8979-2a92cfe7a117)

**Comment by Artrajz** [comment]
是的，其实你可以通过在请求的时候指定`id`，就不用通过更改`config.py`来切换speaker

**Comment by gzmasterpulse** [comment]
> 在config.py中填写espeak的dll路径即可解决 例如Windows下路径为`C:\Program Files\eSpeak NG\libespeak-ng.dll`

大佬，在Linux环的Docker部署如何配置和安装espeak

**Comment by Artrajz** [comment]
docker里我应该写了安装espeak-ng命令，你可以在docker容器终端里输入`espeak-ng --version`确认是否安装。linux环境下安装espeak会自动配置环境变量，所以不需要手动配置dll路径，直接使用就可以了。
