### ISSUE TITLE
请问大佬，怎么能将本项目部署在另一个主机上呢

### ISSUE THREAD

**Issue by Ly2817** [Artrajz/vits-simple-api#3]
就是两个服务器，因为我部署chat-bot的服务器配置太低了，而且硬盘容量也不够，这个项目如果部署在了另一个服务器上改怎么去访问呢，有没有什么具体的思路呀，或者我该百度些什么内容呢，问题有点低级，麻烦你了

**Comment by Ly2817** [comment]
我用的是docker一键部署的脚本，这个脚本运行完成之后，项目文件夹中有一个config.py的文件夹！我把这个文件夹改成config.py的python文件项目才能正常运行，这个是不是bug呀

**Comment by Artrajz** [comment]
> 我用的是docker一键部署的脚本，这个脚本运行完成之后，项目文件夹中有一个config.py的文件夹！我把这个文件夹改成config.py的python文件项目才能正常运行，这个是不是bug呀
是的这是个bug，原因是docker在复制引用文件时复制成了文件夹。目前我还没找到解决办法，所以在一键脚本中加入了拉取前就从仓库里下载config.py

**Comment by Artrajz** [comment]
> 就是两个服务器，因为我部署chat-bot的服务器配置太低了，而且硬盘容量也不够，这个项目如果部署在了另一个服务器上改怎么去访问呢，有没有什么具体的思路呀，或者我该百度些什么内容呢，问题有点低级，麻烦你了

你需要一台拥有公网IP的服务器，docker部署后通过这个公网ip加端口进行访问。没有公网IP可以使用frp之类的内网穿透

**Comment by Ly2817** [comment]
模型推理时服务器无响应
可能是同时处理多个推理任务导致CPU堵塞，可以尝试在voice.py中取消以下两行代码的注释，意思是让pytorch只使用1个物理CPU核心，防止一个任务抢占过多CPU资源。

import torch
torch.set_num_threads(1)

docker该怎么设置这个呢？运行之后服务器就连接不上了，亚马逊云

**Comment by Artrajz** [comment]
> 模型推理时服务器无响应
> 可能是同时处理多个推理任务导致CPU堵塞，可以尝试在voice.py中取消以下两行代码的注释，意思是让pytorch只使用1个物理CPU核心，防止一个任务抢占过多CPU资源。
> 
> import torch
> torch.set_num_threads(1)
> 
> docker该怎么设置这个呢？运行之后服务器就连接不上了，亚马逊云

在/var/lib/docker下找到镜像的目录，可能会有很多个目录，你可以一个个找或者搜一下有没有什么命令可以直接找到（我也还不是很懂docker）
你的情况是运行之后还没开始推理就无响应了吗？
这个方法只适合于同时处理多个任务时避免假死，会使推理速度变慢，其实不是一个很好的解决方法。

**Comment by Ly2817** [comment]
是的，就是开始转换语音之后，服务器就无法链接了，等待很久也依旧无法链接，必须得重启服务器之后才能通过ssh重新链接

**Comment by Ly2817** [comment]
现在已经更换服务器了，换了一个2个内核，2.5g内存的正在部署
