### ISSUE TITLE
使用日文进行对话的时候，如果中间夹杂有汉字或者平假名，会跳过汉字或者平假名

### ISSUE THREAD

**Issue by stormdragongardin** [Artrajz/vits-simple-api#30]

**Comment by Artrajz** [comment]
测试了一下并不会发生跳过的情况，如果是bug的话，请给予更多信息能让我在本地复现，谢谢。

**Comment by stormdragongardin** [comment]
确实不是这边的问题 是我接入的bot的问题，具体可以看这个issue：https://github.com/lss233/chatgpt-mirai-qq-bot/issues/732
