### ISSUE TITLE
加入amr格式音频输出

### ISSUE THREAD

**Issue by t4wefan** [Artrajz/vits-simple-api#31]
部分平台（如qq）需要使用amr格式才能发送音频，使用其他格式需要用ffmpeg转码成amr，不如在服务端自动转码，省掉前端流程

**Comment by Artrajz** [comment]
qq用silk就可以直接发送了

**Comment by t4wefan** [comment]
> qq用silk就可以直接发送了

可能是我的协议问题，我这大概只能发送amr格式

**Comment by Artrajz** [comment]
我去查了下，可能是我换了个转silk的python库的问题，之前用的库是可以转支持qq的silk，明天再测试一下。

**Comment by Artrajz** [comment]
测试结果是库没问题，转出来的silk格式也是支持微信和QQ的，编码都是SILK_V3，文件头和尾也做了特殊处理，只不过微信和qq的语音文件后缀改成了amr或者slk。按理说我这里转的silk都是可以直接发送的。

**Comment by 906051999** [comment]
> 测试结果是库没问题，转出来的silk格式也是支持微信和QQ的，编码都是SILK_V3，文件头和尾也做了特殊处理，只不过微信和qq的语音文件后缀改成了amr或者slk。按理说我这里转的silk都是可以直接发送的。

我这边尝试的话，qq收到的是`[CQ:record,file=base64://]`

**Comment by 906051999** [comment]
> 测试结果是库没问题，转出来的silk格式也是支持微信和QQ的，编码都是SILK_V3，文件头和尾也做了特殊处理，只不过微信和qq的语音文件后缀改成了amr或者slk。按理说我这里转的silk都是可以直接发送的。

发现问题了，是因为生成的silk文件大小是0

**Comment by Artrajz** [comment]
> > 测试结果是库没问题，转出来的silk格式也是支持微信和QQ的，编码都是SILK_V3，文件头和尾也做了特殊处理，只不过微信和qq的语音文件后缀改成了amr或者slk。按理说我这里转的silk都是可以直接发送的。
> 
> 发现问题了，是因为生成的silk文件大小是0

检查一下是否是语言问题导致生成的音频是0kb，可以用其他格式看看
