### ISSUE TITLE
在huggingface上部署如何部署项目

### ISSUE THREAD

**Issue by d4renk** [Artrajz/vits-simple-api#32]
在服务器上运行VITS模型需要满足较高的运行环境要求，而本地电脑不可能一直运行不关机。相比之下，Hugging Face提供的免费配置能够轻松地运行一个VITS项目。

**Comment by Artrajz** [comment]
我也在Hugging Face试过部署，但是失败了，感觉Hugging Face只能部署带webui的项目

**Comment by Artrajz** [comment]
不知道hf可不可以直接克隆仓库。自己的模型放到Model文件夹里，然后修改config.py里的路径。

**Comment by Artrajz** [comment]
https://huggingface.co/spaces/Artrajz/vits-simple-api

**Comment by Artrajz** [comment]
增加参数`length`，可以看看文档

**Comment by Artrajz** [comment]
访问`http://127.0.0.1:23456/voice/speakers`

**Comment by Artrajz** [comment]
`paimon_6k.json`中的`symbols`有问题，其实我已经上传了这个模型在`Model/paimon`里，并修改好了一个可用的json文件，两个模型只有名字不同而已。
