### ISSUE TITLE
对接lss233的qqbot出现问题

### ISSUE THREAD

**Issue by yimrjotunn** [Artrajz/vits-simple-api#33]
![image](https://user-images.githubusercontent.com/113271544/236406811-17fbb1d3-2427-4f9a-98d4-780005ee1211.png)
大佬，好像是因为/voice/speakers  id的返回值格式变了，qqbot的切换语音找不到对应的音色了，这个我直接改代码然后重新打包镜像就可以了吗

**Comment by Artrajz** [comment]
是的，找docker镜像的目录直接改一下也可以，项目在容器的`/app`里，改回原来的是`{new_id: name}`

**Comment by yimrjotunn** [comment]
已解决，感谢大佬
