### ISSUE TITLE
大佬请教一下，我用wechat机器人请求vits-simple-api，反馈语音合成失败，该如何解决。

### ISSUE THREAD

**Issue by cgnannan** [Artrajz/vits-simple-api#36]
大佬您好，最近在测试微信机器人的语音合成方案，在调用咱们家的vist-simple-api时遇到了点问题，想请教您。

前置确认
 1.我确认我运行的是最新版本的代码，并且安装了所需的依赖
   搜索issues中是否已存在类似问题

 2.我已经搜索过issues，没有跟我遇到的问题相关的issue

操作系统类型?
Windows 10 专业版(21H2)

运行的python版本是?
python 3.10.8

复现步骤 🕹
启动终端——>激活环境变量(fort)——>python app.py——>给微信机器人发语音——>请求失败

问题描述 😯
  在微信机器人项目(https://github.com/zhayujie/chatgpt-on-wechat)  中调用仓库的语音合成api,现实语音合成失败。
![IMG_99673FB09C89-1](https://github.com/Artrajz/vits-simple-api/assets/54965656/d08cebba-8d21-4f7e-875e-1be820c2fda2)

终端日志 📒
127.0.0.1 - - [14/May/2023 13:12:40] "POST /voice HTTP/1.1" 400 -

<img width="829" alt="Screen Shot 2023-05-14 at 1 14 15 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/15fd772a-c533-4550-aa78-cdd112dd1bcc">

**Comment by Artrajz** [comment]
看看是不是post请求的代码写错了，可以把微信机器人项目里的post方法单独拿出来测试一下

**Comment by cgnannan** [comment]
> 看看是不是post请求的代码写错了，可以把微信机器人项目里的post方法单独拿出来测试一下，`content-type`是`multipart/form-data`


谢谢大佬，您判断的很准，我看微信机器人请求vist代码，post方法中api的url地址引用错了，修正后vits能接到请求了。
<img width="1673" alt="Screen Shot 2023-05-14 at 2 16 18 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/dc3378ca-5606-4363-963f-038580110432">


但是新问题产生了，我接到了vits发来的wav格式语音文件，容量15B(时长0秒),点击播放听不到声音。大佬，是不是因为我说中文，而vits的Model中我没有配套中文模型库的原因？亦或是语音自动识别等参数设置错误的原因？

![IMG_649D1D36B806-1](https://github.com/Artrajz/vits-simple-api/assets/54965656/e97cf0dc-2ca3-40ac-9afd-dba470b96438)

![IMG_DBFED63D6A31-1](https://github.com/Artrajz/vits-simple-api/assets/54965656/f6831c1e-97d2-45d4-a5b2-3a9214b23764)

**Comment by Artrajz** [comment]
我的建议是先单独测试vist-simple-api能否正常工作，发送请求返回的语音是否正常。不这样我无法确定是哪个环节出现了问题。
请求的语音也要确保模型支持该语言，这个可以在http://127.0.0.1:23456/voice/speakers里面看到

**Comment by cgnannan** [comment]
> 我的建议是先单独测试vits-simple-api能否正常工作，发送请求返回的语音是否正常。不这样我无法确定是哪个环节出现了问题。 请求的语音也要确保模型支持该语言，这个可以在[http://127.0.0.1:23456/voice/speakers里面看到](http://127.0.0.1:23456/voice/speakers%E9%87%8C%E9%9D%A2%E7%9C%8B%E5%88%B0)

python app.py后，终端显示日志如下：

**Comment by cgnannan** [comment]
> 我的建议是先单独测试vits-simple-api能否正常工作，发送请求返回的语音是否正常。不这样我无法确定是哪个环节出现了问题。 请求的语音也要确保模型支持该语言，这个可以在[http://127.0.0.1:23456/voice/speakers里面看到](http://127.0.0.1:23456/voice/speakers%E9%87%8C%E9%9D%A2%E7%9C%8B%E5%88%B0)

大佬，我单独运行vits-simpe-api数据库的python app.py后，终端显示如下日志：
127.0.0.1 - - [14/May/2023 16:11:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2023 16:11:03] "GET /favicon.ico HTTP/1.1" 404 -

在网页打开http://127.0.0.1:23456/，显示如下：
<img width="1680" alt="Screen Shot 2023-05-14 at 4 16 19 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/08d98afe-881c-4b43-9359-131e93e84833">

在页面打开[http://127.0.0.1:23456/voice/speakers，显示如下：
<img width="1680" alt="Screen Shot 2023-05-14 at 4 17 55 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/4d6a9fe9-3da2-4cfd-adc2-8f7bbcd612c9">

是不是在配置vits-simple-api的时候，还是有错误的操作

**Comment by Artrajz** [comment]
应该是忘记配置模型了，没有模型用不了。vits-simpe-api里不带模型，模型要另外下载

**Comment by Artrajz** [comment]
> > 看看是不是post请求的代码写错了，可以把微信机器人项目里的post方法单独拿出来测试一下，`content-type`是`multipart/form-data`
> 
> 谢谢大佬，您判断的很准，我看微信机器人请求vits-simple-api代码，post方法中api的url地址引用错了，修正后vits能接到请求了。 <img alt="Screen Shot 2023-05-14 at 2 16 18 PM" width="1673" src="https://user-images.githubusercontent.com/54965656/238170829-dc3378ca-5606-4363-963f-038580110432.png">
> 
> 但是新问题产生了，我接到了vits-simple-api发来的wav格式语音文件，容量15B(时长0秒),点击播放听不到声音。大佬，是不是因为我说中文，而vits的Model中我没有配套中文模型库的原因？亦或是语音自动识别等参数设置错误的原因？
> 
> 用汉语、日语和英语连续发了三个语音，回复的都是15B大小、0秒时长，听不到声音的语音文件。
> 
> ![IMG_FB87804E406F-1](https://user-images.githubusercontent.com/54965656/238171410-abeb57a8-ade6-47b5-8c12-2a1abf8fba18.jpeg) ![IMG_20D2D7ED2514-1](https://user-images.githubusercontent.com/54965656/238171420-f0fe5f9e-bc7c-4263-986e-a92780062c5d.jpeg)

刚刚没注意看，这个url没有写错，确实是要请求`http://127.0.0.1/voice`。
另外正常来说vits的请求应该会有logging产生的日志，但在你的截图中没有看到。然后我本地尝试在config.py中不填写模型路径的时，发现logging无法正常工作，这应该是个bug，我正在研究如何解决。

**Comment by cgnannan** [comment]
> 应该是忘记配置模型了，没有模型用不了。vits-simple-api里不带模型，模型要另外下载

大佬，按照readme的流程和目录规范，已经准备好Model且在config.py中配置了对应的路径。
<img width="1680" alt="Screen Shot 2023-05-14 at 5 35 04 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/9b6fd9c5-c701-4184-b738-7d4f42335707">

python app.py，在网页打开以下地址
http://127.0.0.1:23456/
http://127.0.0.1:23456/voice/speakers

仍然如下图所示
<img width="1672" alt="Screen Shot 2023-05-14 at 5 40 09 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/50b72654-e75f-4162-9683-4090678f6791">

<img width="1677" alt="Screen Shot 2023-05-14 at 5 39 46 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/139ae4f2-6e70-4ee9-a05a-582915a29576">

**Comment by Artrajz** [comment]
要在`MODEL_LIST`里面填写模型路径，你圈的地方是我写的注释

**Comment by cgnannan** [comment]
> 要在`MODEL_LIST`里面填写模型路径，你圈的地方是我写的注释

在MODEL_LIST中填写模型路径后，运行时，终端窗口提示类型错误。大佬，是否我需要直接写绝对路径？
<img width="1670" alt="Screen Shot 2023-05-14 at 6 00 10 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/6d4bffe0-d88b-4d00-bc23-bb1e57901f6f">

**Comment by Artrajz** [comment]
这个是hubert模型被识别成了w2v2模型，config.json是否模型对应的文件。另外如果只需要语音合成的话其实hubert模型没有用

**Comment by cgnannan** [comment]
> 这个是hubert模型被识别成了w2v2模型，config.json是否是模型对应的文件。另外如果只需要语音合成的话其实hubert模型没有用
 模型和对应的配置文件是从您推荐的仓库下载的
![Screen Shot 2023-05-14 at 6 28 43 PM](https://github.com/Artrajz/vits-simple-api/assets/54965656/56b49e79-42a5-4d36-b5bc-f8dc2854556a)

git pull了您最新的代码，运行后识别到模型了，但仍然报错。
(fort) E:\Fort\WechatBot\vits-simple-api>python app.py
INFO:root:Loaded checkpoint 'E:\Fort\WechatBot\vits-simple-api/Model/Nene_Nanami_Rong_Tang/1026_epochs.pth' (iteration None)
Traceback (most recent call last):
  File "E:\Fort\WechatBot\vits-simple-api\app.py", line 28, in <module>
    tts = merge_model(app.config["MODEL_LIST"])
  File "E:\Fort\WechatBot\vits-simple-api\utils\merge.py", line 53, in merge_model
    obj = vits(model=i[0], config=i[1])
  File "E:\Fort\WechatBot\vits-simple-api\voice.py", line 54, in __init__
    self.load_model(model, model_)
  File "E:\Fort\WechatBot\vits-simple-api\voice.py", line 65, in load_model
    self.emotion_reference = np.load(model_)
  File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\numpy\lib\npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Artrajz** [comment]
噢，你下的Nene_Nanami_Rong_Tang是w2v2模型，但第三个位置应该填写npy文件，例如`[ABS_PATH+"/Model/w2v2-vits/1026_epochs.pth", ABS_PATH+"/Model/w2v2-vits/config.json", ABS_PATH+"/all_emotions.npy"],`不同的模型一定要遵循注释里的说明来填写

**Comment by cgnannan** [comment]
> 噢，你下的Nene_Nanami_Rong_Tang是w2v2模型，但第三个位置应该填写npy文件，例如`[ABS_PATH+"/Model/w2v2-vits/1026_epochs.pth", ABS_PATH+"/Model/w2v2-vits/config.json", ABS_PATH+"/all_emotions.npy"],`不同的模型一定要遵循注释里的说明来填写

大佬，重新检查并匹配了模型，运行后，终端显示如下
<img width="1651" alt="Screen Shot 2023-05-14 at 6 55 43 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/8479399c-884f-4e8a-96fd-319d2494d493">

访问
http://127.0.0.1:23456
http://127.0.0.1:23456/voice/speakers
网页显示如下
<img width="1677" alt="Screen Shot 2023-05-14 at 6 57 38 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/289b4ab5-5091-447a-bb50-a07b8bcb4ae1">
<img width="1673" alt="Screen Shot 2023-05-14 at 6 57 03 PM" src="https://github.com/Artrajz/vits-simple-api/assets/54965656/5d634b27-e824-4e01-8014-d6c191bc64e3">

者是否意味着已经成功运行vist-simple-api了？

**Comment by Artrajz** [comment]
是的

**Comment by cgnannan** [comment]
> 是的

谢谢大佬指点，我现在去试试微信机器人请求vits-simple-api.

**Comment by cgnannan** [comment]
> 是的

微信机器人能请求vits-simple-api,但是提示缺少pyopenjtalk依赖库。我pip install pyopenjtalk，怎么都装不上
(fort) E:\Fort\WechatBot\vits-simple-api>pip3 install pyopenjtalk
Collecting pyopenjtalk
  Using cached pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "E:\Fort\WechatBot\vits-simple-api\fort\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\win10\AppData\Local\Temp\pip-build-env-it0pfaq3\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\win10\AppData\Local\Temp\pip-build-env-it0pfaq3\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\win10\AppData\Local\Temp\pip-build-env-it0pfaq3\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\win10\AppData\Local\Temp\pip-build-env-it0pfaq3\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Artrajz** [comment]
试试`pip3 install openjtalk==0.3.0.dev2`
或者[下载](https://pypi.org/project/openjtalk/0.3.0.dev2/#files)对应你的系统和python版本的whl再用pip install安装

**Comment by cgnannan** [comment]
> 下载

大佬可以啦，现在机器人能正确返回语音啦。真是太感谢啦，占用您一下午时间。您细致、耐心、专业的解决方案，真是让人佩服啊。

![IMG_849A512594DC-1](https://github.com/Artrajz/vits-simple-api/assets/54965656/426f6221-d7b9-4d93-a111-e4f12d8adae5)

**Comment by Artrajz** [comment]
不客气
