### ISSUE TITLE
Mac M1 pip install error when installing openjtalk>=0.3.0.dev2

### ISSUE THREAD

**Issue by kimyLee** [Artrajz/vits-simple-api#38]
it seems something go wrong when installing packages:

(py30) zhonghaoli@MacBook-Pro-14-inch-2021 vits-simple-api % pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting numba (from -r requirements.txt (line 1))
  Using cached numba-0.57.0-cp310-cp310-macosx_11_0_arm64.whl (2.5 MB)
Collecting librosa (from -r requirements.txt (line 2))
  Using cached librosa-0.10.0.post2-py3-none-any.whl (253 kB)
Collecting numpy==1.23.3 (from -r requirements.txt (line 3))
  Using cached numpy-1.23.3-cp310-cp310-macosx_11_0_arm64.whl (13.3 MB)
Collecting scipy (from -r requirements.txt (line 4))
  Using cached scipy-1.10.1-cp310-cp310-macosx_12_0_arm64.whl (28.8 MB)
Collecting torch (from -r requirements.txt (line 5))
  Using cached torch-2.0.1-cp310-none-macosx_11_0_arm64.whl (55.8 MB)
Collecting unidecode (from -r requirements.txt (line 6))
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting openjtalk==0.3.0.dev2 (from -r requirements.txt (line 7))
  Using cached openjtalk-0.3.0.dev2.tar.gz (24.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/zhonghaoli/miniforge3/envs/py30/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>

**Comment by Artrajz** [comment]
You may need to check if cmake is working properly.

**Comment by kimyLee** [comment]
您好，来信已收到，我会尽快给您回复。

**Comment by kimyLee** [comment]
can just show me some possible way to solve it  ? 😂

**Comment by Artrajz** [comment]
You can try installing cmake by `pip install cmake` or downloading and installing it from the [cmake official website](https://cmake.org/download/). Note that having both of them installed simultaneously may cause issues.

**Comment by kimyLee** [comment]
well, actually I have camke installed, and I upgrade it just now. the problem still exist, same problem when I install openjtalk alone. I think it may need some config params like cmake. anyway, I will look for wider help , thanks~

**Comment by Artrajz** [comment]
After installing cmake, I was able to build OpenJTalk smoothly without any additional steps. However, I have not tried this on a Mac, so I can only offer my suggestion. 😿

**Comment by kimyLee** [comment]
well, I found the solution.
since I use conda for python environment, I set the python to x64 and install again, everything go well···
`CONDA_SUBDIR=osx-64 conda create -n py30_64 python=3.10`
