### ISSUE TITLE
发现三个bug？

### ISSUE THREAD

**Issue by 40740** [Artrajz/vits-simple-api#40]
我测试一下了，很棒！感谢大佬！
不过好像有三个bug（或许是我的方式不对？）
1.方言无法失败会自动转为普通话，比如我用粤语；[GD]XXXXXXXX[GD] , 无效，会读成普通话；
2.用老大的post，发现ssml 会出现这样的bug：
```python
Traceback (most recent call last):
  File "1.py", line 5, in <module>
    voice_ssml(smm);
  File "D:\ai\vits\bmss_fy\vits-simple-api-windows\post.py", line 151, in voice_ssml
    fname = re.findall("filename=(.+)", res.headers["Content-Disposition"])[0]
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
``` 
3.（不是bug哈哈哈）原emotion可以使用单个npy文件使用情绪，是否后续追加，也支持单个npy？

最后感谢付出。

**Comment by 40740** [comment]
我尝试读了代码，因为对python非常不熟悉，基本上很难处理。

**Comment by Artrajz** [comment]
1.不同的语言需要模型支持，比如使用方言需要该模型是用方言数据训练的。如果你使用的是粤语模型但还是发生这个错误，那可能是我的bug，可以发给我研究一下。
2.需要看看你发送的ssml以及vits-simple-api的报错，从post报错来看很难找到问题。
3.npy文件存储的是numpy数组，理论上来说可以将多个npy文件合并为一个，实现将新的情感数据追加到原npy中，也比较方便。

**Comment by 40740** [comment]
1.粤语用的是https://huggingface.co/spaces/skytnt/moe-tts 这个的model14 有粤语，大佬可以试试。
2.smml是这样的：
```python
smm='<speak lang="zh" format="wav" length="1.2" model="w2v2-vits"><voice id="0" emotion="1">这几天心里颇不宁静。</voice></speak>'
``` 
2.1.vits-simple-api 好像没
3.这样的话，在操作上如果想多加一个情绪，要先追加到原npy，多了一步，哈哈哈相对上麻烦了，毕竟都想偷懒一下。（戳手手）

另外，我用的快速部署包，不知道是不是因为一键包没同步最新的代码问题。

**Comment by Artrajz** [comment]
这样的话我之后加个能同时加载不同npy的方法吧。快速部署包里的是旧代码，需要手动更新代码。

**Comment by Artrajz** [comment]
我尝试使用了[仓库](https://huggingface.co/spaces/skytnt/moe-tts)里的`saved_model/17`，发现是我忘记添加chinese_dialect_cleaners的判断所致，现已修复 e72da740ca38850b35bb3942d943981dbdc49993
同时加载不同npy现在也支持了 af26b22b900f62bc05b88ae1043284c9f95a2c97

**Comment by 40740** [comment]
哇，神仙老大，辛苦了。orz 感谢付出。 SMMLL 那个我还没测出来，我用最新代码需要安装环境，卡在fasttext 一直安装不上，在和chatgpt 找解决方法。 老大也可以试试 SMMLL  最新代码是不是可行。

**Comment by Artrajz** [comment]
我本地是可以用ssml的，fasttext快速部署包里也装了，如果你是想自己装的话我在文档里也写了Windows安装fasttext的方法

**Comment by 40740** [comment]
同一个模型和配置文件，但是加载多个npy报错，用之前单个就可以，
![image](https://github.com/Artrajz/vits-simple-api/assets/39937268/34e64b6c-2243-4ad2-b957-67b042dd8fb8)

```
Traceback (most recent call last):
  File "D:\ai\vits\api\app.py", line 28, in <module>
    tts = merge_model(app.config["MODEL_LIST"])
  File "D:\ai\vits\api\utils\merge.py", line 96, in merge_model
    obj = vits(model=i[0], config=i[1], model_=i[2])
  File "D:\ai\vits\api\voice.py", line 54, in __init__
    self.load_model(model, model_)
  File "D:\ai\vits\api\voice.py", line 69, in load_model
    self.emotion_reference = np.append(self.emotion_reference, tmp, axis=0)
  File "<__array_function__ internals>", line 180, in append
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\function_base.py", line 5444, in append
    return concatenate((arr, values), axis=axis)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
```

**Comment by Artrajz** [comment]
是npy维度的问题，可以把这个npy文件发给我看看吗

**Comment by 40740** [comment]
[bigshuaige.zip](https://github.com/Artrajz/vits-simple-api/files/11515237/bigshuaige.zip)
修改后缀即可

**Comment by 40740** [comment]
> 是npy维度的问题，可以把这个npy文件发给我看吗

不过是同一样npy文件，用[]就不能加载，去掉就可以加载。

 感觉可以和MoeGoe那样后加载npy文件

**Comment by 40740** [comment]
> MoeGoe

MoeGoe就是有这两个功能哈哈哈，所以哈哈哈。

对了，我用方言测试了，还是不行，会直接把[GD][SH] 读出来，还是普通话。

**Comment by Artrajz** [comment]
看下日志

**Comment by Artrajz** [comment]
方言不支持自动识别，因为都是中文汉字没法区分😢，所以要指定lang=gd

**Comment by 40740** [comment]
> 方言不支持自动识别，因为都是中文汉字没法区分😢，所以要指定lang=gd 如果是输入的文本本身就带[GD]，可以用lang=mix

ok 了  是我没操作对，感谢感谢
