### ISSUE TITLE
如何对接lss大佬的bot项目

### ISSUE THREAD

**Issue by Katerina0926** [Artrajz/vits-simple-api#41]
使用docker启动
![image](https://github.com/Artrajz/vits-simple-api/assets/104199092/9f7dfdeb-ca16-4773-ace7-3f159ce7d33d)
![image](https://github.com/Artrajz/vits-simple-api/assets/104199092/3b2e811e-8551-4fd4-97ef-7ff693ac7b5b)
moegoe-config.json是个文件夹形式,该如何正常启动呢 直接部署启动也会返回500的报错

**Comment by Artrajz** [comment]
docker compose的bug，把这个文件夹删除，然后把代码里的config.json手动放到到这个位置

**Comment by Katerina0926** [comment]
新版本是config.py:/app/config.json吗,启动成功但是会出现如下报错
![image](https://github.com/Artrajz/vits-simple-api/assets/104199092/afb1ca2b-93af-4713-9c45-e1c17add7880)

**Comment by Artrajz** [comment]
我是说换我这边的新版本，你所用的分支里的check接口也是旧的，和现在的chatqq-bot不兼容

**Comment by Katerina0926** [comment]
![image](https://github.com/Artrajz/vits-simple-api/assets/104199092/b2aba805-47fd-4f06-9e26-97f109ae4016)
![image](https://github.com/Artrajz/vits-simple-api/assets/104199092/743e622d-6c94-41aa-885d-2fc39d0cb399)
![image](https://github.com/Artrajz/vits-simple-api/assets/104199092/64f0e4f7-debb-4565-98ad-908e94911aac)
单独使用也出现报错了

**Comment by Artrajz** [comment]
报错显示23456端口已分配，kill掉使用了23456端口的进程或者换一个端口使用

**Comment by Katerina0926** [comment]
如何查看是否启动成功和其中的日志啊

**Comment by Artrajz** [comment]
`docker-compose logs -f`

**Comment by Artrajz** [comment]
docker compose的命令`docker-compose logs -f`

**Comment by Katerina0926** [comment]
![image](https://github.com/Artrajz/vits-simple-api/assets/104199092/689b4b49-998d-4243-a5a0-373b079e9ff8)
请问这是启动失败了吗

**Comment by Artrajz** [comment]
一切正常
