### ISSUE TITLE
老大哦，还是建议加上 音频来调节情感吧，在MoeGoe来回跳转着实麻烦哈哈哈

### ISSUE THREAD

**Issue by 40740** [Artrajz/vits-simple-api#42]
有时候需要新增一个情绪的npy ，需要先到MoeGoe去生成npy，还是觉得建议加上 音频来调节情感吧，来回跳转很麻烦哈哈哈，而且
也还是要依靠MoeGoe，如vits-simple-api有生成npy的功能，那就完全独立了，就可以删掉MoeGoe了哈哈哈。

**Comment by 40740** [comment]
我简单修改了一下config.py，把所有的情感npy文件放到一个文件夹，遍历，调用，这样就省去了手动一个一个写。（小白写的，可供参考。）

```
NPY_PATH = ABS_PATH +"/npy"  # 文件夹的绝对路径
npy_files = []

for file in os.listdir(NPY_PATH):
    if file.endswith(".npy"):
        npy_files.append(ABS_PATH + file)
``` 

上次老大你说每次转换都需要上传参考语音觉得麻烦，也可以单独弄一个wav2npy的接口，批量生成到npy文件夹中，用之前先生成，就不用每次都要上传参考语音啦。

这个需求觉得是很需要的，要不然每次都需要去MoeGoe，这样vits-simple-api也无法真正独立使用。

**Comment by Artrajz** [comment]
从文件夹批量读取这个可以加一个。
把生成npy写成接口的话，考虑到部署到服务器之后人人都可以调用这个接口，而这在某些情况下是不必要的（比如npy只生成到本地）。如果只生成到本地的npy文件夹的话，单独写一个脚本生成会不会更合适？或者是有上传音频到api接口然后返回npy文件的需求？

**Comment by 40740** [comment]
我目前的解决方式就是，自己用官方的训练时批量生成npy的文件，单独拎出来，目前算是单独的脚本生成npy吧；这样就完全不需要MoeGoe配合使用了。

上传音频到api接口然后返回npy文件 正是我的需求。

我看MoeGoe的逻辑也是这样，参考音频也先生成npy到本地，然后再读取该npy。

不过，因为我是自己用，早上自己搞了一下，可以本地单独生成npy，基本满足自己用了。

**Comment by Artrajz** [comment]
已更新 16a1995ac6ab1ce80defbd95b9606b2cd9f2d721，如果遇到bug请告知我
