### ISSUE TITLE
docker 一键部署问题

### ISSUE THREAD

**Issue by Logan147** [Artrajz/vits-simple-api#43]
我无法通过那个脚本部署docker镜像，我看了那个脚本里的内容 docker compose pull 后面什么都没有，是还没开发吗

**Comment by Logan147** [comment]
我想在radxa zero 和树莓派之类的便携的arm开发板上用vits可以提供一下相关的docker支持吗，感谢

**Comment by Artrajz** [comment]
`docker compose pull`是通过下载的`yaml`文件来拉取的，根据你所说的应该是架构不同导致无法部署，后续会增加arm架构的docker版本。但由于我也是新手所以要先研究一下。

**Comment by Logan147** [comment]
好的，🙏大佬发布arm支持的docker一键部署镜像



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月23日(星期二) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Artrajz/vits-simple-api] docker 一键部署问题 (Issue #43)





 
docker compose pull是通过下载的yaml文件来拉取的，根据你所说的应该是架构不同导致无法部署，后续会增加arm架构的docker版本。但由于我也是新手所以要先研究一下。

**Comment by Logan147** [comment]
多谢大佬提供arm开发板等嵌入式linux 的docker支持
