### ISSUE TITLE
getattr()报错

### ISSUE THREAD

**Issue by BaiWinterSnow** [Artrajz/vits-simple-api#45]
运行app.py后,getattr返回一个报错.提示 attribute name must be string.
![`MW 3%WH ES@H8ID%~T@FP5](https://github.com/Artrajz/vits-simple-api/assets/128290072/8ed65cb6-7c67-42a1-8289-790ca7465ba4)
配置文件路径设置如下:
MODEL_LIST = [
    # VITS
    [ABS_PATH + "/Model/Xin/G_32000.pth", ABS_PATH + "/Model/Xin/config.json"],
    #[ABS_PATH + "/Model/Zero_no_tsukaima/1158_epochs.pth", ABS_PATH + "/Model/Zero_no_tsukaima/config.json"],
    #[ABS_PATH + "/Model/g/G_953000.pth", ABS_PATH + "/Model/g/config.json"],
    # HuBert-VITS (Need to configure HUBERT_SOFT_MODEL)
    #[ABS_PATH + "/Model/louise/360_epochs.pth", ABS_PATH + "/Model/louise/config.json"],
    # W2V2-VITS (Need to configure DIMENSIONAL_EMOTION_NPY)
    #[ABS_PATH + "/Model/w2v2-vits/1026_epochs.pth", ABS_PATH + "/Model/w2v2-vits/config.json"],
]

**Comment by Artrajz** [comment]
可否看一下你的json文件中的speaker

**Comment by BaiWinterSnow** [comment]
json文件中的speaker:
![USHMV}%W9C YIM05QGG O](https://github.com/Artrajz/vits-simple-api/assets/128290072/e2e373b6-61f2-43c8-bade-2b37bf9d16ea)

**Comment by Artrajz** [comment]
把这个字典改成列表的格式就行了，内容是speaker的名称，不用写编号

**Comment by BaiWinterSnow** [comment]
> 把这个字典改成列表的格式就行了，内容是speaker的名称，不用写编号

已经解决,十分感谢.
