### ISSUE TITLE
单纯使用转化功能不训练，需要的服务器性能是什么

### ISSUE THREAD

**Issue by hisou** [Artrajz/vits-simple-api#46]
我服务器是centOS 8，尝试启动项目：
```
python3 app.py 
torch:2.0.1+cu117 GPU_available:False
device:cpu device.type:cpu
```
到这里CPU占用和硬盘IO飙升，很快导致`io_util`达到峰值，服务器无法响应了。关掉终端重新登录也无法响应，只能重启服务器。死机的时候看了一眼硬盘读取是285508kb/s，这是读取模型吗？总共我就导入了三个pth模型。
有什么好的办法吗？（已经多次尝试，必死机）

**Comment by hisou** [comment]
![image](https://github.com/Artrajz/vits-simple-api/assets/13644483/5fa44a47-c50c-4e74-be66-777c5fb22352)
附一张监控图

**Comment by Artrajz** [comment]
我在2核2g的服务器上可以加载多个模型并正常运行，但是由于内存不够有时也会出现和你一样的情况而宕机。我想应该是内存不足的问题，也许4g以上会比较好？

**Comment by Artrajz** [comment]
如何性能实在不够可以试试白嫖hugging face的(

**Comment by hisou** [comment]
我自己已经准备了想使用的角色语音模型，肯定不会考虑用其他模型了。我先问下云客服要往哪个方向升级

**Comment by hisou** [comment]
怪了，我的也是2核2G的为什么就必卡，我问了客服他说CPU和磁盘占用很高，内存占用正常的，这我就犹豫要不要升4G内存了…

**Comment by Artrajz** [comment]
你的pth模型大小是多少？

**Comment by hisou** [comment]
很巧的是每个都是152MB，那时候打包下载的。我觉得再怎么说本程序也不可能用得到4核U

**Comment by Artrajz** [comment]
那应该不是模型大小的问题。因为我在2核的服务器上直接加载多个四五百mb的模型也是加载不了，而一百mb的可以加载好几个。我在hugging face上使用免费配置也是2核的，我看了下日志也没有发生过死机的情况。会不会是你的服务器上有别的程序也在占用资源？

**Comment by hisou** [comment]
第一次是有，因为我要跑miraiQQ，本来就是打算mirai那边调用这边vits生成语音文件，然后mirai发送语音消息。我以为这边是不怎么占用的，打算两个服务常开。
但是第一次死机后重启了服务器肯定就是什么都没开了，这时候直接启动本程序也是会卡死的。
如果以后两个程序确实难以一起使用，我这个方案就得想办法换了

**Comment by Artrajz** [comment]
miraiQQ这些服务应该不怎么占资源，我也是开一个bot加一个vits，应该没问题的。我查了下国内的云服务器还分共享型、突发型、独享型什么的，性能不一定一样，不知道你的服务器是不是这个原因。

**Comment by hisou** [comment]
刚才客服进一步排查说是内存满了导致，现在在生成vmcore继续研究问题，我再等等看

**Comment by hisou** [comment]
加到4G内存成功启动了，访问也能返回200，可以开始测试最大能加载多大多少个模型了

**Comment by hisou** [comment]
4G内存下，我目前加载了450M模型一个150M模型4个，单是启动服务就会占用到3G内存，但是还是能正常接收语音转换请求。
但是似乎观察到一个问题，每次请求都会加大内存占用100M左右，不会释放，同时有多个请求发过来的话很快就让服务器卡死了。
也许作者可以调查一下是不是真的有内存持续占用不释放的情况？

**Comment by hisou** [comment]
我的miraiQQ是java写的，虚拟机占得高，应该是java+本程序=3g占用

**Comment by Artrajz** [comment]
看了几天，检查过代码感觉没有会内存泄漏的地方，反复测试了之后发现刚开始的几次调用内存增长比较快，第一次调用会增长大概300mb，后面使用循环多次调用，调用结束后的内存只会小幅度增长，至于为什么会增长以我目前的水平找不出来 😢。也使用过`del`语句和`gc.collect()`测试，结果也是差不多的。感觉都是函数里的临时变量，调用完后python应该会在合适的时机自动回收内存的。
