### ISSUE TITLE
linux版本的speakers请求和windows版本的返回json不一样？

### ISSUE THREAD

**Issue by hisou** [Artrajz/vits-simple-api#47]
`wget http://127.0.0.1:23456/voice/speakers` 只会得到id和name两个属性，而且没有属性名，更像map？
`{"HuBert-VITS":[],"VITS":[{"0":"爱丽丝"},{"1":"日奈"},{"2":"星野"},{"3":"优香"}],"W2V2-VITS":[]}`

**Comment by Artrajz** [comment]
Windows上用的是快速部署包吗，里面是旧代码，更新一下就好了

**Comment by hisou** [comment]
其实我感觉windows上的
`[{"name":"爱丽丝","id":0,"lang":["zh","ja"]},{"name":"日奈","id":1,"lang":["zh","ja"]},{"name":"星野2","id":2,"lang":["ja"]},{"name":"星野","id":3,"lang":["ja"]}]`
写出了具体的属性名的更好用，linux这个格式每个JSONObject都是一个键值对，没有属性名一时间我还懵了

**Comment by hisou** [comment]
> 没有不一样，你应该是没更新代码

那现在是哪种格式的返回是新的？

**Comment by Artrajz** [comment]
> 其实我感觉windows上的 `[{"name":"爱丽丝","id":0,"lang":["zh","ja"]},{"name":"日奈","id":1,"lang":["zh","ja"]},{"name":"星野2","id":2,"lang":["ja"]},{"name":"星野","id":3,"lang":["ja"]}]` 写出了具体的属性名的更好用，linux这个格式每个JSONObject都是一个键值对，没有属性名一时间我还懵了

这一种

**Comment by hisou** [comment]
那我重新chrome一次再改一下代码
