### ISSUE TITLE
宝子，好像有一个bug

### ISSUE THREAD

**Issue by 40740** [Artrajz/vits-simple-api#48]
当我测试这个的时候，它自动把一些词识别为日语。
并且就算我在加上[ZH]包裹也还是复现。

log如下：

DEBUG:vits-simple-api:[[EN]ZH][EN][ZH] 君不见，[ZH][JA]黄河之水天上来，[JA][ZH]奔流到海不复回。君不见，高堂明镜悲白发， 朝如青丝暮成雪[[ZH][EN]ZH][EN]

**Comment by Artrajz** [comment]
默认情况下lang为auto，如果不需要自动识别改成zh就好了

**Comment by 40740** [comment]
> 自动识别还存在一定误差。默认情况下lang为auto，如果不需要自动识别改成zh就好了

好的 ，谢谢宝子
