### ISSUE TITLE
老大加一个流式处理？

### ISSUE THREAD

**Issue by 40740** [Artrajz/vits-simple-api#55]
老大加一个流式处理？是否能实现流式响应？

**Comment by Artrajz** [comment]
现在是利用原来的文本分段推理来实现流式响应，先推理出一段就可以播放。使用cpu推理还是比较慢的，等待时间就是推理第一段文本需要的时间。不过推理长文本时，流式响应的速度优势还是很明显。测试使用GPU推理（1060显卡）荷塘月色全文，非流式需要12s才能播放，流式需要1~2s就可以开始播放音频。

所以现在的瓶颈是第一段文本的推理速度，看过PaddleSpeech的流式合成，感觉还是得从模型上解决，但是我不会😭

**Comment by 40740** [comment]
我一开始也是尝试长文本的时候也是用分段式，不过会影响合成读音效果（一句话和好几句话的说话语气似乎有出入），如果是模型上解决那就没办法了。谢谢老大。
