### ISSUE TITLE
请问为什么链接打开之后什么内容都没有呢

### ISSUE THREAD

**Issue by klaylizhe** [Artrajz/vits-simple-api#56]
cmd里会显示 "GET /favicon.ico HTTP/1.1" 404 -

**Comment by Artrajz** [comment]
favicon没有这个是正常的。截图看看你说的没有内容的情况，后台，配置文件

**Comment by jinkexue** [comment]
同样的问题

**Comment by Artrajz** [comment]
> 同样的问题 “GET / HTTP/1.1" 200 - 浏览器页面空白

访问首页浏览器应该会显示`vits-simple-api`字样，确定什么都没有吗？语音请求是否正常呢？

你们给的信息太少我也看不出什么问题 🤣

**Comment by Artrajz** [comment]
请求是正常的，但是加载了0个speakers，请检查模型配置

**Comment by jinkexue** [comment]
建议有几点补充：1. window 下载包 说明下不含模型，最好把默认模型加进去 2.config 注释 有点误导。 修改后模型加载成功，但页面也是空白，这个是不带ui界面吗

**Comment by Artrajz** [comment]
> 1. window 下载包 说明下不含模型，最好把默认模型加进去 

下载包只是提供一个已配置好的环境，打包好的下载包体积已经很大了，模型不方便放进去

> 2.config 注释 有点误导。 修改后模型加载成功，但页面也是空白，这个是不带ui界面吗

以前的config.py注释确实写的不清晰，后面有所修改。我说明了下载包里的代码不是最新的，现在新的代码里不加载模型是会有警告的。目前git仓库里的代码是不带ui界面的，hugging face上为了方便使用才写了个简单的页面。

**Comment by jinkexue** [comment]
替换了新过来的 static  templates app.py 三个地方 出现报错： File "D:\AI\vits-simple-api\app.py", line 56, in index
    "speakers": tts.voice_speakers
AttributeError: 'tuple' object has no attribute 'voice_speakers'

**Comment by Artrajz** [comment]
其他代码有更新吗，部署包的代码是5月份的

**Comment by jinkexue** [comment]
除了config,其他全部替换，目前报错：  File "D:\AI\vits-simple-api\text\cleaners.py", line 4, in <module>
    from phonemizer import phonemize
ModuleNotFoundError: No module named 'phonemizer'

**Comment by Artrajz** [comment]
有依赖没装上，可以使用在根目录下使用`py310\python.exe -m pip install -r requirements.txt`进行更新。

我正在打包一个新的部署包，稍后发布

**Comment by jinkexue** [comment]
ok 了 感谢 楼主。另外请问使用 so-vits-svc 训练出来的pth 和 config 不能直接使用吗？

**Comment by Artrajz** [comment]
不可以的，本项目是用于vits语音合成的推理，现在还不兼容so-vits-svc之类的声线转换

**Comment by jinkexue** [comment]
> 不可以的，本项目是用于vits语音合成的推理，现在还不兼容so-vits-svc之类的声线转换

意思不能使用发布的这个去训练？如果要训练声音素材推荐用哪个？

**Comment by Artrajz** [comment]
可以用这个项目[VITS-fast-fine-tuning](https://github.com/Plachtaa/VITS-fast-fine-tuning)

**Comment by jinkexue** [comment]
> 可以用这个项目[VITS-fast-fine-tuning](https://github.com/Plachtaa/VITS-fast-fine-tuning)
好像是二次元风格，有正常对话效果的项目推荐吗？

**Comment by Artrajz** [comment]
这个训练项目并没有限定风格就是二次元，只是作者提供的底模是使用二次元音频数据集训练的，使用自己的数据集在此基础上微调得到的效果也是正常的。

可能你想说的是训练出来的模型带了日语口音？那也可以不使用底模从零开始训练，不过对你所使用的数据集质量要求较高。

**Comment by Artrajz** [comment]
> 训练好直接增加路径到配置文件modellist 提示 File "D:\AI\vits-simple-api\utils\utils.py", line 29, in getitem
return getattr(self, key)
TypeError: getattr(): attribute name must be string

要在模型的config.json中把speakers改为列表格式。
