### ISSUE TITLE
vits和chatgpt QQ启动后，发消息未有ai语音消息  只有文本  

### ISSUE THREAD

**Issue by HieinAV** [Artrajz/vits-simple-api#61]
vits和chatgpt QQ启动后，发消息未有ai语音消息  只有文本
![1](https://github.com/Artrajz/vits-simple-api/assets/82797048/71d0b054-4c3e-4c49-8729-28df02d60fef)
![2](https://github.com/Artrajz/vits-simple-api/assets/82797048/a9e866e2-5c66-4972-a4a0-22a21bff23e7)
![3](https://github.com/Artrajz/vits-simple-api/assets/82797048/6b099341-2ec6-4961-ad56-93917625fd00)
chatgpt qq一直在开始计时

**Comment by HieinAV** [comment]
求解决方法

**Comment by HieinAV** [comment]
vits终端启动发送的链接是正常可以在网页启动

**Comment by Artrajz** [comment]
根据日志来看，chatgpt QQ没有调用到语音服务。请检查chatgpt QQ的配置，以及所在机器是否能正常访问语音服务。
