### ISSUE TITLE
我下载了一个日语的模型，但是说话只有喘气声音，没有发音，是config设置有问题吗

### ISSUE THREAD

**Issue by alice184516** [Artrajz/vits-simple-api#64]

**Comment by alice184516** [comment]
![image](https://github.com/Artrajz/vits-simple-api/assets/117461719/dbdcb30e-f8c2-4e3b-b7c6-a5e4964634df)

**Comment by alice184516** [comment]
要怎样设置让它能识别中文，中文的好像都只有喘气声音，只有字母和数字才发音

**Comment by Artrajz** [comment]
首先能不能说中文要看模型本身支不支持中文，其次，如果支持中文的话，`config.py`中就不能把语言定死为日语，可以设置成`auto`或者`zh`。同样的，如果直接设置成`zh`就又说不了日语了。另外本项目中日语应该是`ja`而不是`jp`。
