### ISSUE TITLE
感谢大佬，请问如何训练说话人？

### ISSUE THREAD

**Issue by mdys** [Artrajz/vits-simple-api#67]
如题，想要个正常预期环境下的声音，当前的都太二次元了。 麻烦能说下如何训练 ，谢谢

**Comment by Artrajz** [comment]
本项目只有推理功能，要训练的话可以看看vits-fast-fine-tuning这个项目。具体训练步骤可以看项目里的说明，一般是使用作者提供的预训练模型进行微调。预训练模型觉得太二次元也没关系，迭代步数多一点之后也会贴合训练样本的声线。如果样本质量高的话也可以从头训练。

**Comment by xiaoyin199** [comment]
请问：
vits_chinese数据集怎么准备，准备自己的数据集，自己的声音训练，要照着那1w句读一遍吗还是有什么办法；

**Comment by Artrajz** [comment]
> 请问： vits_chinese数据集怎么准备，准备自己的数据集，自己的声音训练，要照着那1w句读一遍吗还是有什么办法；

你可以对着标贝那个数据集文本录音，把音频替换成自己的，其他原封不动
