### ISSUE TITLE
未成功加载w2v2模型

### ISSUE THREAD

**Issue by aurxs** [Artrajz/vits-simple-api#68]
cli内显示成功加载的4个角色，但webui未显示，尝试使用api调用也未成功
<img width="1280" alt="fa024ddb592ce1002965d877824e646" src="https://github.com/Artrajz/vits-simple-api/assets/79303639/36a7463c-67fe-4100-8a34-ff43106fe566">
<img width="1253" alt="34bf79c99384ec7ad9c2051d9b99325" src="https://github.com/Artrajz/vits-simple-api/assets/79303639/5cba6ce4-77ec-48b8-985a-c02288a0f2ae">

**Comment by Artrajz** [comment]
对不起懒癌犯了😢

其实这是正常的，因为webui当时只写了vits的调用。现在可以先用api调用w2v2，之后会更新webui。（也是嫌自己网页写的丑陋一直拖着）

**Comment by aurxs** [comment]
> 对不起懒癌犯了😢
> 
> 其实这是正常的，因为webui当时只写了vits的调用，之后会更新webui。（也是嫌自己网页写的丑陋一直拖着）
> 
> api调用也失败的话，有报错信息吗？

![image](https://github.com/Artrajz/vits-simple-api/assets/79303639/063abc79-c8cf-4890-ba6c-fbc0527b32b9)
不知道调用格式是否正确，但是按图中的地址调用不成功

**Comment by Artrajz** [comment]
w2v2调用的地址不一样
`http://127.0.0.1:23456/voice/w2v2-vits?text=こんにちは&id=3&emotion=111`

**Comment by aurxs** [comment]
谢谢大佬，解决了，希望能尽快适配webui
