### ISSUE TITLE
BERT-VITS2支持

### ISSUE THREAD

**Issue by aurxs** [Artrajz/vits-simple-api#69]
新出的BERT-VITS2效果很好，有考虑过集成到vits-sample-api里面吗

**Comment by Artrajz** [comment]
已更新 054a669d8d44b1768bc71b319715980bcbdcec1e
后续有bug可以反馈

**Comment by 40740** [comment]
加载模型出错。 合成音频是微电流声音。在模型在原仓库项目是可以成功合成的。

erta-wwm-ext-large were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
INFO:vits-simple-api:Loading finished.
error, enc_p.emb.weight is not in the checkpoint
error, enc_p.tone_emb.weight is not in the checkpoint
error, enc_p.language_emb.weight is not in the checkpoint
error, enc_p.bert_proj.weight is not in the checkpoint
error, enc_p.bert_proj.bias is not in the checkpoint
error, enc_p.encoder.cond_pre.weight is not in the checkpoint
error, enc_p.encoder.cond_pre.bias is not in the checkpoint

**Comment by aurxs** [comment]
> 加载模型出错。 合成音频是微电流声音。在模型在原仓库项目是可以成功合成的。
> 
> 
> 
> erta-wwm-ext-large were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
> 
> - This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> 
> - This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> 
> INFO:vits-simple-api:Loading finished.
> 
> error, enc_p.emb.weight is not in the checkpoint
> 
> error, enc_p.tone_emb.weight is not in the checkpoint
> 
> error, enc_p.language_emb.weight is not in the checkpoint
> 
> error, enc_p.bert_proj.weight is not in the checkpoint
> 
> error, enc_p.bert_proj.bias is not in the checkpoint
> 
> error, enc_p.encoder.cond_pre.weight is not in the checkpoint
> 
> error, enc_p.encoder.cond_pre.bias is not in the checkpoint

哥，开新issue去，别在我这楼下面发啊（
