### ISSUE TITLE
bert_vits2 加载模型失败

### ISSUE THREAD

**Issue by 40740** [Artrajz/vits-simple-api#71]
加载模型出错。 合成音频是微电流声音。在模型在原仓库项目是可以成功合成的。

erta-wwm-ext-large were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']

This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
INFO:vits-simple-api:Loading finished.
error, enc_p.emb.weight is not in the checkpoint
error, enc_p.tone_emb.weight is not in the checkpoint
error, enc_p.language_emb.weight is not in the checkpoint
error, enc_p.bert_proj.weight is not in the checkpoint
error, enc_p.bert_proj.bias is not in the checkpoint
error, enc_p.encoder.cond_pre.weight is not in the checkpoint
error, enc_p.encoder.cond_pre.bias is not in the checkpoint

**Comment by Artrajz** [comment]
加载的模型是G开头的吗

**Comment by 40740** [comment]
> 加载的模型是G开头的吗

是的，原项目是可以成功加载，并且成功合成语音。

不过最新测试发现，虽然加载错误，但是有问题，模型中有两个发音人，但是只要一个有能成功合成，另一个是不能合成的，只有轻微电流声音；估计是就加载这部分失败；

而且我发现合成的效果不知道为什么也比原项目效果差，同一模型，同一参数。

**Comment by Artrajz** [comment]
方便发一下你出问题的模型吗，因为我自己训练出来的模型能正常用的
