### ISSUE TITLE
加载bert vits2模型报错

### ISSUE THREAD

**Issue by hongdaikun** [Artrajz/vits-simple-api#72]
版本：安装部署包后，解压主线代码覆盖。
直接加载bert vits2模型报错：INFO:apscheduler.scheduler:Scheduler started
INFO:vits-simple-api:Loading chinese-roberta-wwm-ext-large...
Some weights of the model checkpoint at C:\vits-simple-api/bert_vits2/bert/chinese-roberta-wwm-ext-large were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
INFO:vits-simple-api:Loading finished.
error, ref_enc.convs.0.bias is not in the checkpoint
error, ref_enc.convs.0.weight_g is not in the checkpoint
error, ref_enc.convs.0.weight_v is not in the checkpoint
error, ref_enc.convs.1.bias is not in the checkpoint
error, ref_enc.convs.1.weight_g is not in the checkpoint
error, ref_enc.convs.1.weight_v is not in the checkpoint
error, ref_enc.convs.2.bias is not in the checkpoint
error, ref_enc.convs.2.weight_g is not in the checkpoint
error, ref_enc.convs.2.weight_v is not in the checkpoint
error, ref_enc.convs.3.bias is not in the checkpoint
error, ref_enc.convs.3.weight_g is not in the checkpoint
error, ref_enc.convs.3.weight_v is not in the checkpoint
error, ref_enc.convs.4.bias is not in the checkpoint
error, ref_enc.convs.4.weight_g is not in the checkpoint
error, ref_enc.convs.4.weight_v is not in the checkpoint
error, ref_enc.convs.5.bias is not in the checkpoint
error, ref_enc.convs.5.weight_g is not in the checkpoint
error, ref_enc.convs.5.weight_v is not in the checkpoint
error, ref_enc.gru.weight_ih_l0 is not in the checkpoint
error, ref_enc.gru.weight_hh_l0 is not in the checkpoint
error, ref_enc.gru.bias_ih_l0 is not in the checkpoint
error, ref_enc.gru.bias_hh_l0 is not in the checkpoint
error, ref_enc.proj.weight is not in the checkpoint
error, ref_enc.proj.bias is not in the checkpoint
INFO:root:Loaded checkpoint 'C:\vits-simple-api/bert_vits2/G_5000.pth' (iteration 114)
INFO:vits-simple-api:torch:2.0.1+cu117 cuda_available:True
INFO:vits-simple-api:device:cuda device.type:cuda
INFO:vits-simple-api:[Bert-VITS2] 1 speakers
INFO:vits-simple-api:1 speakers in total.
INFO:apscheduler.scheduler:Added job "clean_task" to job store "default"
 * Serving Flask app 'app'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:23456
 * Running on http://192.168.31.163:23456
INFO:werkzeug:Press CTRL+C to quit

**Comment by Artrajz** [comment]
这个报错我目前不知道是什么问题。我用部署包里的环境，尝试加载自己训练的模型和别人的模型都可以正常加载，也不知道如何复现出这个报错。如果可以的话能发一下你加载出错的模型给我测试一下吗？

**Comment by hongdaikun** [comment]
https://www.123pan.com/s/gezLVv-kNt0h.html提取码:5NS9。麻烦了。不过我觉得可能不是模型的问题。因为我测试的所有模型原项目都没问题。

**Comment by Artrajz** [comment]
我使用你的模型进行测试，在原项目和本项目中都会报同样的错误，经过测试在`bert_vits2/models.py`中第646行`if n_speakers > 1:`修改为`if n_speakers >= 1:`后，原项目和本项目中均可正常加载。原因可能是模型训练时使用的是多人模型的训练方法，但config.json中的`n_speakers`却为1，导致`model.py`中按单人模型的结构来加载。修改代码后可以解决，但我不确定这是否是最佳解决方案。
