### ISSUE TITLE
Bert-VITS2 access url?

### ISSUE THREAD

**Issue by willis** [Artrajz/vits-simple-api#76]
Bert-VITS2 access url?
Bert-VITS2 download url?
# [ABS_PATH + "/bert_vits2/G_9000.pth", ABS_PATH + "/bert_vits2/config.json"],

**Comment by Artrajz** [comment]
Sorry, there is currently no publicly available Bert-VITS2 model for inference. The path` [ABS_PATH + "/bert_vits2/G_9000.pth", ABS_PATH + "/bert_vits2/config.json"]` is just an example.
