### ISSUE TITLE
1.11版的Bert-VITS2是否可以只是用中文的模型？

### ISSUE THREAD

**Issue by AlayaQQ** [Artrajz/vits-simple-api#86]
现在使用只训练了中文的模型，声音有问题。

**Comment by Artrajz** [comment]
不确定你问的问题。只训练了中文的模型是指Bert-VITS2 1.0.1之前的版本吗？还是指使用Bert-VITS2 1.1.1但只用了中文数据集进行训练？

不管是哪个版本，如果模型加载出现问题日志中会有相应的警告，根据警告，在模型的config.json中添加对应的`legacy_version`参数以及对应版本，来兼容旧版本的Bert-VITS2。

**Comment by dfmjndm** [comment]
> 不确定你问的问题。只训练了中文的模型是指Bert-VITS2 1.0.1之前的版本吗？还是指使用Bert-VITS2 1.1.1但只用了中文数据集进行训练？
> 
> 不管是哪个版本，如果模型加载出现问题日志中会有相应的警告，根据警告，在模型的config.json中添加对应的`legacy_version`参数以及对应版本，来兼容旧版本的Bert-VITS2。

请问legacy_version是加入config的model：{}里面吗

**Comment by gushuaialan1** [comment]
1.0训练出来的模型跑出来是鸟语  config里面的data参数也设置正确了

**Comment by Artrajz** [comment]
> 1.0训练出来的模型跑出来是鸟语  config里面的data参数也设置正确了

更新到最新代码，版本参数改成version，再试试，还是不行的话，发日志看一下。

**Comment by Artrajz** [comment]
> > 1.0训练出来的模型跑出来是鸟语  config里面的data参数也设置正确了
> 
> 更新到最新代码，版本参数改成version，版本号写你的1.0，再试试，还是不行的话，发日志看一下。

**Comment by gushuaialan1** [comment]
> > 1.0训练出来的模型跑出来是鸟语  config里面的data参数也设置正确了
> 
> 更新到最新代码，版本参数改成version，版本号写你的1.0，再试试，还是不行的话，发日志看一下。

搞定了，原来是按照你的提示写的"legacy_version": "1.0" 改成"version": "1.0"后正常，感谢！

**Comment by anthonyyuan** [comment]
可以给出一个详细的说明吗，我训练出也是乱说话

**Comment by Artrajz** [comment]
> 可以给出一个详细的说明吗，我训练出也是乱说话

vits-simple-api更新到最新代码，然后在模型的config.json中加入版本号参数，参考https://github.com/Artrajz/vits-simple-api/issues/90#issuecomment-1791969482 其余也没什么了
