### ISSUE TITLE
使用bert_vits2的模型推理时报错

### ISSUE THREAD

**Issue by v3ucn** [Artrajz/vits-simple-api#87]
File "E:\work\vits-simple-api\bert_vits2\text\chinese_bert.py", line 35, in get_bert_feature
    res = model(**inputs, output_hidden_states=True)
NameError: name 'model' is not defined

**Comment by Artrajz** [comment]
检查bert模型下了吗

**Comment by v3ucn** [comment]
刚刚下好了，但是开始报这个错了：

D:\work\vits-simple-api>python app.py
DEBUG:tzlocal:Looking up time zone info from registry
INFO:apscheduler.scheduler:Scheduler started
INFO:vits-simple-api:Loading chinese-roberta-wwm-ext-large...
Some weights of the model checkpoint at D:\work\vits-simple-api/bert_vits2/bert/chinese-roberta-wwm-ext-large were not used when initializing BertForMaskedLM: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
INFO:vits-simple-api:Loading finished.
INFO:vits-simple-api:Loading bert-base-japanese-v3...
ERROR:vits-simple-api:You need to install fugashi to use MecabTokenizer. See https://pypi.org/project/fugashi/ for installation.
ERROR:vits-simple-api:Please download pytorch_model.bin from cl-tohoku/bert-base-japanese-v3.
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\zcxey\AppData\Local\Temp\jieba.cache
DEBUG:jieba:Loading model from cache C:\Users\zcxey\AppData\Local\Temp\jieba.cache
Loading model cost 0.331 seconds.
DEBUG:jieba:Loading model cost 0.331 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
ERROR:vits-simple-api:Uncaught exception
Traceback (most recent call last):
  File "D:\work\vits-simple-api\app.py", line 30, in <module>
    tts = load_model(app.config["MODEL_LIST"])
  File "D:\work\vits-simple-api\utils\load_model.py", line 172, in load_model
    from bert_vits2 import Bert_VITS2
  File "D:\work\vits-simple-api\bert_vits2\__init__.py", line 1, in <module>
    from bert_vits2.bert_vits2 import Bert_VITS2
  File "D:\work\vits-simple-api\bert_vits2\bert_vits2.py", line 8, in <module>
    from bert_vits2.text.cleaner import clean_text
  File "D:\work\vits-simple-api\bert_vits2\text\cleaner.py", line 1, in <module>
    from bert_vits2.text import chinese, japanese, cleaned_text_to_sequence
  File "D:\work\vits-simple-api\bert_vits2\text\japanese.py", line 9, in <module>
    from bert_vits2.text.japanese_bert import tokenizer
ImportError: cannot import name 'tokenizer' from 'bert_vits2.text.japanese_bert' (D:\work\vits-simple-api\bert_vits2\text\japanese_bert.py)

**Comment by v3ucn** [comment]
可以了，貌似时1.1的模型和1.0模型不通用导致的，感谢。
