### ISSUE TITLE
Bert-VITS2是否可以切换版本？

### ISSUE THREAD

**Issue by Joackk** [Artrajz/vits-simple-api#89]
这里下载的别的大佬训练的模型，但是似乎是Bert-VITS21.0训练的，所以和项目里的1.1不兼容，Bert-VITS2版本可以进行切换吗？

**Comment by Artrajz** [comment]
可以的，下载最新的代码，在config.json中的`train`上方，加一行版本号参数`version": "1.0",`保存后启动api。

**Comment by Joackk** [comment]
> 可以的，下载最新的代码，在config.json中的`train`上方，加一行版本号参数`version": "1.0",`保存后启动api。

请问大佬·是vits-simple-api目录下的config.json吗？我在这里没有搜到train关键字啊。我是下载的Releases里的快速部署包。
也就是如果要再切回默认版本只需要把上面那个删掉就好吗？

**Comment by Artrajz** [comment]
是你下载的模型里，一个是.pth，另一个是config.json，是在模型配套的config.json里添加

**Comment by Joackk** [comment]
> 是你下载的模型里，一个是.pth，另一个是config.json，是在模型配套的config.json里添加

soga，感谢大佬，正常了
