### ISSUE TITLE
ssml 协议中 speak 标签属性model 与代码不匹配，代码中为 model_type

### ISSUE THREAD

**Issue by ChenYangY** [Artrajz/vits-simple-api#92]
ssml 协议中 speak 标签属性model 与代码不匹配。代码中为 model_type

[文档](https://github.com/Artrajz/vits-simple-api#ssml-speech-synthesis-markup-language)

[代码](https://github.com/Artrajz/vits-simple-api/blob/main/TTSManager.py#L135C13-L135C13)

**Comment by Artrajz** [comment]
是的，感谢您的提醒！

现已修改文档。
