### ISSUE TITLE
鼓捣几个小时，没有声音。

### ISSUE THREAD

**Issue by KnIfER** [Artrajz/vits-simple-api#95]
下载 vits-simple-api-windows-cpu-v0.6.0-alpha.8.7z 
模型是b站找的：https://www.bilibili.com/read/cv26659988/?from=articleDetail
运行的时候会往 bert_vits2\bert 下载几个g的文件，那是什么。

log，没有报错:
[log.txt](https://github.com/Artrajz/vits-simple-api/files/13361500/log.txt)

**Comment by KnIfER** [comment]
![image](https://github.com/Artrajz/vits-simple-api/assets/11593903/fc5fd479-c4c9-4be5-a3c9-66a9e9905a04)

**Comment by Artrajz** [comment]
运行时如果缺少bert模型则会自动下载补全，bert-vits2顾名思义是融合了bert的vits，缺少bert模型则无法运行。

看了你的日志，其实是有报错的，报错在加载模型的部分。bert-vits2有多版本兼容问题，当然本项目是兼容了各个版本的。根据日志来看你可以试一下添加版本号1.0.1，添加方式可以看文档。

还有日志中报错说加载模型权重失败，可以检查模型是否正确下载，和模型是否被加密。
